export interface PineV6ReferenceSignature {
  params: readonly string[];
  minArgs?: number;
  maxArgs?: number;
  requiredParams?: readonly string[];
  overloads?: readonly (readonly string[])[];
}

export const PINE_V6_REFERENCE_SIGNATURES = {
  input: {
    input: { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'display', 'active'], minArgs: 1 },
    'input.int': {
      params: ['defval', 'title', 'options', 'minval', 'maxval', 'step', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
      overloads: [
        ['defval', 'title', 'minval', 'maxval', 'step', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
        ['defval', 'title', 'options', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
      ],
      minArgs: 1,
    },
    'input.float': {
      params: ['defval', 'title', 'options', 'minval', 'maxval', 'step', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
      overloads: [
        ['defval', 'title', 'minval', 'maxval', 'step', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
        ['defval', 'title', 'options', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'],
      ],
      minArgs: 1,
    },
    'input.bool': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.string': { params: ['defval', 'title', 'options', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.color': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.source': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.timeframe': { params: ['defval', 'title', 'options', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.symbol': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.session': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.price': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.text_area': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.time': { params: ['defval', 'title', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
    'input.enum': { params: ['defval', 'title', 'options', 'tooltip', 'inline', 'group', 'confirm', 'display', 'active'], minArgs: 1 },
  },
  math: {
    'math.abs': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.acos': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.asin': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.atan': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.avg': { params: ['number0', 'number1'], minArgs: 2 },
    'math.ceil': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.clamp': { params: ['val', 'min', 'max'], minArgs: 3, maxArgs: 3 },
    'math.cos': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.exp': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.floor': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.log': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.log10': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.max': { params: ['number0', 'number1'], minArgs: 2 },
    'math.min': { params: ['number0', 'number1'], minArgs: 2 },
    'math.pow': { params: ['base', 'exponent'], minArgs: 2, maxArgs: 2 },
    'math.random': { params: ['min', 'max', 'seed'], minArgs: 0, maxArgs: 3 },
    'math.round': { params: ['number', 'precision'], minArgs: 1, maxArgs: 2 },
    'math.round_to_mintick': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.sign': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.sin': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.sqrt': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.sum': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'math.tan': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.todegrees': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.toradians': { params: ['number'], minArgs: 1, maxArgs: 1 },
    'math.trunc': { params: ['number'], minArgs: 1, maxArgs: 1 },
  },
  str: {
    'str.tostring': { params: ['value', 'format'], minArgs: 1, maxArgs: 2 },
    'str.tonumber': { params: ['string'], minArgs: 1, maxArgs: 1 },
    'str.format_time': { params: ['time', 'format', 'timezone'], minArgs: 0, maxArgs: 3 },
    'str.format': { params: ['format'], minArgs: 1 },
    'str.length': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'str.contains': { params: ['source', 'str'], minArgs: 2, maxArgs: 2 },
    'str.startswith': { params: ['source', 'str'], minArgs: 2, maxArgs: 2 },
    'str.endswith': { params: ['source', 'str'], minArgs: 2, maxArgs: 2 },
    'str.pos': { params: ['source', 'str'], minArgs: 2, maxArgs: 2 },
    'str.substring': { params: ['source', 'begin_pos', 'end_pos'], minArgs: 2, maxArgs: 3 },
    'str.match': { params: ['source', 'regex'], minArgs: 2, maxArgs: 2 },
    'str.repeat': { params: ['source', 'repeat', 'separator'], minArgs: 2, maxArgs: 3 },
    'str.split': { params: ['source', 'separator'], minArgs: 2, maxArgs: 2 },
    'str.upper': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'str.lower': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'str.trim': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'str.replace': { params: ['source', 'target', 'replacement', 'occurrence'], minArgs: 3, maxArgs: 4 },
    'str.replace_all': { params: ['source', 'target', 'replacement'], minArgs: 3, maxArgs: 3 },
  },
  array: {
    'array.new': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_bool': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_box': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_chart_point': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_color': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_float': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_int': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_label': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_line': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_linefill': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_polyline': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_string': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.new_table': { params: ['size', 'initial_value'], minArgs: 0, maxArgs: 2 },
    'array.clear': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.copy': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.first': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.last': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.pop': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.shift': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.size': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.get': { params: ['id', 'index'], minArgs: 2, maxArgs: 2 },
    'array.remove': { params: ['id', 'index'], minArgs: 2, maxArgs: 2 },
    'array.push': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.unshift': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.insert': { params: ['id', 'index', 'value'], minArgs: 3, maxArgs: 3 },
    'array.set': { params: ['id', 'index', 'value'], minArgs: 3, maxArgs: 3 },
    'array.every': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.some': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.binary_search': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.binary_search_leftmost': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.binary_search_rightmost': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.includes': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.indexof': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.lastindexof': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.concat': { params: ['id', 'id2'], minArgs: 2, maxArgs: 2 },
    'array.fill': { params: ['id', 'value', 'index_from', 'index_to'], minArgs: 2, maxArgs: 4 },
    'array.join': { params: ['id', 'separator'], minArgs: 1, maxArgs: 2 },
    'array.reverse': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.slice': { params: ['id', 'index_from', 'index_to'], minArgs: 3, maxArgs: 3 },
    'array.sort': { params: ['id', 'order', 'sort_field'], minArgs: 1, maxArgs: 3 },
    'array.sort_indices': { params: ['id', 'order'], minArgs: 1, maxArgs: 2 },
    'array.abs': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.avg': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.max': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.median': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.min': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.mode': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.range': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.standardize': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.sum': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'array.stdev': { params: ['id', 'biased'], minArgs: 1, maxArgs: 2 },
    'array.variance': { params: ['id', 'biased'], minArgs: 1, maxArgs: 2 },
    'array.percentile_linear_interpolation': { params: ['id', 'percentage'], minArgs: 2, maxArgs: 2 },
    'array.percentile_nearest_rank': { params: ['id', 'percentage'], minArgs: 2, maxArgs: 2 },
    'array.covariance': { params: ['id1', 'id2', 'biased'], minArgs: 2, maxArgs: 3 },
    'array.percentrank': { params: ['id', 'value'], minArgs: 2, maxArgs: 2 },
    'array.from': { params: [], minArgs: 0 },
  },
  matrix: {
    'matrix.new': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.new_bool': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.new_color': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.new_float': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.new_int': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.new_string': { params: ['rows', 'columns', 'initial_value'], minArgs: 0, maxArgs: 3 },
    'matrix.columns': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.elements_count': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_valid': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.rows': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.get': { params: ['id', 'row', 'column'], minArgs: 3, maxArgs: 3 },
    'matrix.set': { params: ['id', 'row', 'column', 'value'], minArgs: 4, maxArgs: 4 },
    'matrix.fill': { params: ['id', 'value', 'from_row', 'to_row', 'from_column', 'to_column'], minArgs: 2, maxArgs: 6 },
    'matrix.reshape': { params: ['id', 'rows', 'columns'], minArgs: 3, maxArgs: 3 },
    'matrix.reverse': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.add_row': { params: ['id', 'row', 'array_id'], minArgs: 1, maxArgs: 3 },
    'matrix.add_col': { params: ['id', 'column', 'array_id'], minArgs: 1, maxArgs: 3 },
    'matrix.add_column': { params: ['id', 'column', 'array_id'], minArgs: 1, maxArgs: 3 },
    'matrix.remove_row': { params: ['id', 'row'], minArgs: 2, maxArgs: 2 },
    'matrix.remove_col': { params: ['id', 'column'], minArgs: 2, maxArgs: 2 },
    'matrix.remove_column': { params: ['id', 'column'], minArgs: 2, maxArgs: 2 },
    'matrix.swap_rows': { params: ['id', 'row1', 'row2'], minArgs: 3, maxArgs: 3 },
    'matrix.swap_columns': { params: ['id', 'column1', 'column2'], minArgs: 3, maxArgs: 3 },
    'matrix.concat': { params: ['id1', 'id2'], minArgs: 2, maxArgs: 2 },
    'matrix.submatrix': { params: ['id', 'from_row', 'to_row', 'from_column', 'to_column'], minArgs: 1, maxArgs: 5 },
    'matrix.copy': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.transpose': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.row': { params: ['id', 'row'], minArgs: 2, maxArgs: 2 },
    'matrix.col': { params: ['id', 'column'], minArgs: 2, maxArgs: 2 },
    'matrix.column': { params: ['id', 'column'], minArgs: 2, maxArgs: 2 },
    'matrix.avg': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.det': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.eigenvalues': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.eigenvectors': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.inv': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.max': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.median': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.min': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.mode': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.pinv': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.rank': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.trace': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.diff': { params: ['id1', 'id2'], minArgs: 2, maxArgs: 2 },
    'matrix.kron': { params: ['id1', 'id2'], minArgs: 2, maxArgs: 2 },
    'matrix.mult': { params: ['id1', 'id2'], minArgs: 2, maxArgs: 2 },
    'matrix.sum': { params: ['id1', 'id2'], minArgs: 2, maxArgs: 2 },
    'matrix.pow': { params: ['id', 'power'], minArgs: 2, maxArgs: 2 },
    'matrix.sort': { params: ['id', 'column', 'order', 'sort_field'], minArgs: 1, maxArgs: 4 },
    'matrix.is_antidiagonal': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_antisymmetric': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_binary': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_diagonal': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_identity': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_square': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_stochastic': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_symmetric': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_triangular': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'matrix.is_zero': { params: ['id'], minArgs: 1, maxArgs: 1 },
  },
  map: {
    'map.clear': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'map.contains': { params: ['id', 'key'], minArgs: 2, maxArgs: 2 },
    'map.copy': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'map.get': { params: ['id', 'key'], minArgs: 2, maxArgs: 2 },
    'map.keys': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'map.new': { params: [], minArgs: 0, maxArgs: 0 },
    'map.put': { params: ['id', 'key', 'value'], minArgs: 3, maxArgs: 3 },
    'map.put_all': { params: ['id', 'id2'], minArgs: 2, maxArgs: 2 },
    'map.remove': { params: ['id', 'key'], minArgs: 2, maxArgs: 2 },
    'map.size': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'map.values': { params: ['id'], minArgs: 1, maxArgs: 1 },
  },
  ticker: {
    'ticker.new': { params: ['prefix', 'ticker', 'session', 'adjustment', 'backadjustment', 'settlement_as_close'], minArgs: 2, maxArgs: 6 },
    'ticker.modify': { params: ['tickerid', 'session', 'adjustment', 'backadjustment', 'settlement_as_close'], minArgs: 1, maxArgs: 5 },
    'ticker.standard': { params: ['symbol'], minArgs: 1, maxArgs: 1 },
    'ticker.inherit': { params: ['from_tickerid', 'symbol'], minArgs: 2, maxArgs: 2 },
    'ticker.heikinashi': { params: ['symbol'], minArgs: 1, maxArgs: 1 },
    'ticker.renko': { params: ['symbol', 'style', 'param', 'request_wicks', 'source'], minArgs: 3, maxArgs: 5 },
    'ticker.linebreak': { params: ['symbol', 'number_of_lines'], minArgs: 2, maxArgs: 2 },
    'ticker.kagi': { params: ['symbol', 'style', 'param'], minArgs: 3, maxArgs: 3 },
    'ticker.pointfigure': { params: ['symbol', 'source', 'style', 'param', 'reversal'], minArgs: 5, maxArgs: 5 },
  },
  timeframe: {
    'timeframe.change': { params: ['timeframe'], minArgs: 0, maxArgs: 1 },
    'timeframe.from_seconds': { params: ['seconds'], minArgs: 1, maxArgs: 1 },
    'timeframe.in_seconds': { params: ['timeframe'], minArgs: 0, maxArgs: 1 },
    'timeframe.to_seconds': { params: ['timeframe'], minArgs: 0, maxArgs: 1 },
  },
  chart: {
    'chart.point.copy': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'chart.point.from_index': { params: ['index', 'price'], minArgs: 2, maxArgs: 2 },
    'chart.point.from_time': { params: ['time', 'price'], minArgs: 2, maxArgs: 2 },
    'chart.point.new': { params: ['time', 'index', 'price'], minArgs: 3, maxArgs: 3 },
    'chart.point.now': { params: ['price'], minArgs: 0, maxArgs: 1 },
  },
  color: {
    color: { params: ['red', 'green', 'blue', 'transp'], minArgs: 3, maxArgs: 4 },
    'color.new': { params: ['color', 'transp'], minArgs: 2, maxArgs: 2 },
    'color.rgb': { params: ['red', 'green', 'blue', 'transp'], minArgs: 3, maxArgs: 4 },
    'color.r': { params: ['color'], minArgs: 1, maxArgs: 1 },
    'color.g': { params: ['color'], minArgs: 1, maxArgs: 1 },
    'color.b': { params: ['color'], minArgs: 1, maxArgs: 1 },
    'color.t': { params: ['color'], minArgs: 1, maxArgs: 1 },
    'color.from_gradient': { params: ['value', 'bottom_value', 'top_value', 'bottom_color', 'top_color'], minArgs: 5, maxArgs: 5 },
  },
  ta: {
    'ta.alma': { params: ['series', 'length', 'offset', 'sigma', 'floor'], minArgs: 4, maxArgs: 5 },
    'ta.atr': { params: ['length'], minArgs: 1, maxArgs: 1 },
    'ta.bar_index': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'ta.barssince': { params: ['condition'], minArgs: 1, maxArgs: 1 },
    'ta.bb': { params: ['series', 'length', 'mult'], minArgs: 3, maxArgs: 3 },
    'ta.bbw': { params: ['series', 'length', 'mult'], minArgs: 3, maxArgs: 3 },
    'ta.valuewhen': { params: ['condition', 'source', 'occurrence'], minArgs: 3, maxArgs: 3 },
    'ta.change': { params: ['source', 'length'], minArgs: 1, maxArgs: 2 },
    'ta.cci': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.cmo': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.cum': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'ta.crossover': { params: ['source1', 'source2'], minArgs: 2, maxArgs: 2 },
    'ta.crossunder': { params: ['source1', 'source2'], minArgs: 2, maxArgs: 2 },
    'ta.cross': { params: ['source1', 'source2'], minArgs: 2, maxArgs: 2 },
    'ta.correlation': { params: ['source1', 'source2', 'length'], minArgs: 3, maxArgs: 3 },
    'ta.covariance': { params: ['source1', 'source2', 'length'], minArgs: 3, maxArgs: 3 },
    'ta.cog': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.dev': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.adx': { params: ['diLength', 'adxSmoothing'], minArgs: 1, maxArgs: 2 },
    'ta.dmi': { params: ['diLength', 'adxSmoothing'], minArgs: 2, maxArgs: 2 },
    'ta.ema': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.hma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.highest': { params: ['source', 'length'], minArgs: 1, maxArgs: 2, requiredParams: ['length'] },
    'ta.lowest': { params: ['source', 'length'], minArgs: 1, maxArgs: 2, requiredParams: ['length'] },
    'ta.highestbars': { params: ['source', 'length'], minArgs: 1, maxArgs: 2, requiredParams: ['length'] },
    'ta.lowestbars': { params: ['source', 'length'], minArgs: 1, maxArgs: 2, requiredParams: ['length'] },
    'ta.kc': { params: ['series', 'length', 'mult', 'useTrueRange'], minArgs: 3, maxArgs: 4 },
    'ta.kcw': { params: ['series', 'length', 'mult', 'useTrueRange'], minArgs: 3, maxArgs: 4 },
    'ta.median': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.mfi': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.macd': { params: ['source', 'fastlen', 'slowlen', 'siglen'], minArgs: 4, maxArgs: 4 },
    'ta.mode': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.obv': { params: ['source', 'volume'], minArgs: 0, maxArgs: 2 },
    'ta.percentile_nearest_rank': { params: ['source', 'length', 'percentage'], minArgs: 3, maxArgs: 3 },
    'ta.percentile_linear_interpolation': { params: ['source', 'length', 'percentage'], minArgs: 3, maxArgs: 3 },
    'ta.percentrank': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.pivot_point_levels': { params: ['type', 'anchor', 'developing'], minArgs: 2, maxArgs: 3 },
    'ta.pivothigh': { params: ['source', 'leftbars', 'rightbars'], minArgs: 2, maxArgs: 3, requiredParams: ['leftbars', 'rightbars'] },
    'ta.pivotlow': { params: ['source', 'leftbars', 'rightbars'], minArgs: 2, maxArgs: 3, requiredParams: ['leftbars', 'rightbars'] },
    'ta.max': { params: ['source1', 'source2'], minArgs: 2, maxArgs: 2 },
    'ta.min': { params: ['source1', 'source2'], minArgs: 2, maxArgs: 2 },
    'ta.mom': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.range': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.rising': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.falling': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.rci': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.rma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.smma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.roc': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.rsi': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.sar': { params: ['start', 'inc', 'max'], minArgs: 3, maxArgs: 3 },
    'ta.sma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.stdev': { params: ['source', 'length', 'biased'], minArgs: 2, maxArgs: 3 },
    'ta.stoch': { params: ['source', 'high', 'low', 'length'], minArgs: 4, maxArgs: 4 },
    'ta.supertrend': { params: ['factor', 'atrPeriod'], minArgs: 2, maxArgs: 2 },
    'ta.swma': { params: ['source'], minArgs: 1, maxArgs: 1 },
    'ta.tr': { params: ['handle_na'], minArgs: 0, maxArgs: 1 },
    'ta.dema': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.tema': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.kst': {
      params: ['source', 'roclength1', 'roclength2', 'roclength3', 'roclength4', 'smalen1', 'smalen2', 'smalen3', 'smalen4', 'signalLength'],
      minArgs: 1,
      maxArgs: 10,
    },
    'ta.tsi': { params: ['source', 'short_length', 'long_length'], minArgs: 3, maxArgs: 3 },
    'ta.variance': { params: ['source', 'length', 'biased'], minArgs: 2, maxArgs: 3 },
    'ta.vwap': { params: ['source', 'anchor', 'stdev_mult'], minArgs: 0, maxArgs: 3 },
    'ta.vwma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.linreg': { params: ['source', 'length', 'offset'], minArgs: 3, maxArgs: 3 },
    'ta.wma': { params: ['source', 'length'], minArgs: 2, maxArgs: 2 },
    'ta.wpr': { params: ['length'], minArgs: 1, maxArgs: 1 },
  },
  request: {
    'request.security': { params: ['symbol', 'timeframe', 'expression', 'gaps', 'lookahead', 'ignore_invalid_symbol', 'currency', 'calc_bars_count'], minArgs: 3 },
    'request.security_lower_tf': { params: ['symbol', 'timeframe', 'expression', 'ignore_invalid_symbol', 'currency', 'ignore_invalid_timeframe', 'calc_bars_count'], minArgs: 3 },
    'request.currency_rate': { params: ['from', 'to', 'ignore_invalid_currency'], minArgs: 2 },
    'request.dividends': { params: ['ticker', 'field', 'gaps', 'lookahead', 'ignore_invalid_symbol', 'currency'], minArgs: 1 },
    'request.splits': { params: ['ticker', 'field', 'gaps', 'lookahead', 'ignore_invalid_symbol'], minArgs: 1 },
    'request.earnings': { params: ['ticker', 'field', 'gaps', 'lookahead', 'ignore_invalid_symbol', 'currency'], minArgs: 1 },
    'request.financial': { params: ['symbol', 'financial_id', 'period', 'gaps', 'ignore_invalid_symbol', 'currency'], minArgs: 3 },
    'request.economic': { params: ['country_code', 'field', 'gaps', 'ignore_invalid_symbol'], minArgs: 2 },
    'request.quandl': { params: ['ticker', 'gaps', 'index', 'ignore_invalid_symbol'], minArgs: 1 },
    'request.seed': { params: ['source', 'symbol', 'expression', 'ignore_invalid_symbol', 'calc_bars_count'], minArgs: 3 },
    'request.footprint': { params: ['ticks_per_row', 'va_percent', 'imbalance_percent'], minArgs: 2, maxArgs: 3 },
  },
  footprint: {
    'footprint.total_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.buy_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.sell_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.delta': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.rows': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.poc': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.vah': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.val': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'footprint.get_row_by_price': { params: ['id', 'price'], minArgs: 2, maxArgs: 2 },
  },
  volume_row: {
    'volume_row.up_price': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.down_price': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.total_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.buy_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.sell_volume': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.delta': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.has_buy_imbalance': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'volume_row.has_sell_imbalance': { params: ['id'], minArgs: 1, maxArgs: 1 },
  },
  visual: {
    plot: { params: ['series', 'title', 'color', 'linewidth', 'style', 'trackprice', 'histbase', 'offset', 'join', 'editable', 'show_last', 'display', 'format', 'precision', 'force_overlay', 'linestyle'], minArgs: 1 },
    plotbar: { params: ['open', 'high', 'low', 'close', 'title', 'color', 'editable', 'show_last', 'display', 'force_overlay'], minArgs: 4 },
    plotcandle: { params: ['open', 'high', 'low', 'close', 'title', 'color', 'wickcolor', 'editable', 'show_last', 'bordercolor', 'display'], minArgs: 4 },
    plotshape: { params: ['series', 'title', 'style', 'location', 'color', 'offset', 'text', 'textcolor', 'editable', 'size', 'show_last', 'display', 'format', 'precision', 'force_overlay'], minArgs: 1 },
    plotchar: { params: ['series', 'title', 'char', 'location', 'color', 'offset', 'text', 'textcolor', 'editable', 'size', 'show_last', 'display', 'format', 'precision', 'force_overlay'], minArgs: 1 },
    plotarrow: { params: ['series', 'title', 'colorup', 'colordown', 'offset', 'minheight', 'maxheight', 'editable', 'show_last', 'display', 'format', 'precision', 'force_overlay'], minArgs: 1 },
    hline: { params: ['price', 'title', 'color', 'linestyle', 'linewidth', 'editable', 'display'], minArgs: 1 },
    fill: { params: ['plot1', 'plot2', 'color', 'title', 'editable', 'show_last', 'fillgaps', 'display'], minArgs: 3 },
    bgcolor: { params: ['color', 'offset', 'editable', 'show_last', 'title', 'display', 'force_overlay'], minArgs: 1 },
    barcolor: { params: ['color', 'offset', 'editable', 'show_last', 'title', 'display'], minArgs: 1 },
  },
  drawing: {
    'line.new': {
      params: ['x1', 'y1', 'x2', 'y2', 'xloc', 'extend', 'color', 'style', 'width', 'force_overlay'],
      overloads: [['first_point', 'second_point', 'xloc', 'extend', 'color', 'style', 'width', 'force_overlay']],
      minArgs: 4,
      maxArgs: 10,
    },
    'label.new': {
      params: ['x', 'y', 'text', 'xloc', 'yloc', 'color', 'style', 'textcolor', 'size', 'textalign', 'tooltip', 'text_font_family', 'force_overlay', 'text_formatting'],
      overloads: [['point', 'text', 'xloc', 'yloc', 'color', 'style', 'textcolor', 'size', 'textalign', 'tooltip', 'text_font_family', 'force_overlay', 'text_formatting']],
      minArgs: 2,
      maxArgs: 14,
    },
    'box.new': {
      params: ['left', 'top', 'right', 'bottom', 'border_color', 'border_width', 'border_style', 'extend', 'xloc', 'bgcolor', 'text', 'text_size', 'text_color', 'text_halign', 'text_valign', 'text_wrap', 'text_font_family', 'force_overlay', 'text_formatting'],
      overloads: [['top_left', 'bottom_right', 'border_color', 'border_width', 'border_style', 'extend', 'xloc', 'bgcolor', 'text', 'text_size', 'text_color', 'text_halign', 'text_valign', 'text_wrap', 'text_font_family', 'force_overlay', 'text_formatting']],
      minArgs: 4,
      maxArgs: 19,
    },
    'polyline.new': { params: ['points', 'curved', 'closed', 'xloc', 'line_color', 'fill_color', 'line_style', 'line_width', 'force_overlay'], minArgs: 1, maxArgs: 9 },
    'linefill.new': { params: ['line1', 'line2', 'color'], minArgs: 2, maxArgs: 3 },
    'table.new': { params: ['position', 'columns', 'rows', 'bgcolor', 'frame_color', 'frame_width', 'border_color', 'border_width', 'force_overlay'], minArgs: 2, maxArgs: 9, requiredParams: ['columns', 'rows'] },
    'table.cell': { params: ['table_id', 'column', 'row', 'text', 'width', 'height', 'text_color', 'text_halign', 'text_valign', 'text_size', 'bgcolor', 'text_font_family', 'text_formatting', 'tooltip'], minArgs: 3, maxArgs: 14 },
  },
  strategy: {
    strategy: {
      params: [
        'title',
        'shorttitle',
        'overlay',
        'format',
        'precision',
        'scale',
        'pyramiding',
        'calc_on_order_fills',
        'calc_on_every_tick',
        'max_bars_back',
        'backtest_fill_limits_assumption',
        'default_qty_type',
        'default_qty_value',
        'initial_capital',
        'currency',
        'slippage',
        'commission_type',
        'commission_value',
        'process_orders_on_close',
        'close_entries_rule',
        'margin_long',
        'margin_short',
        'explicit_plot_zorder',
        'max_lines_count',
        'max_labels_count',
        'max_boxes_count',
        'risk_free_rate',
        'use_bar_magnifier',
        'fill_orders_on_standard_ohlc',
        'max_polylines_count',
        'dynamic_requests',
        'behind_chart',
      ],
      minArgs: 1,
    },
    'strategy.cancel': { params: ['id'], minArgs: 1, maxArgs: 1 },
    'strategy.cancel_all': { params: [], minArgs: 0, maxArgs: 0 },
    'strategy.close': { params: ['id', 'comment', 'qty', 'qty_percent', 'alert_message', 'immediately', 'disable_alert'], minArgs: 1 },
    'strategy.close_all': { params: ['comment', 'alert_message', 'immediately', 'disable_alert'], minArgs: 0 },
    'strategy.entry': { params: ['id', 'direction', 'qty', 'limit', 'stop', 'oca_name', 'oca_type', 'comment', 'alert_message', 'disable_alert'], minArgs: 2, maxArgs: 10 },
    'strategy.exit': {
      params: [
        'id',
        'from_entry',
        'qty',
        'qty_percent',
        'profit',
        'limit',
        'loss',
        'stop',
        'trail_price',
        'trail_points',
        'trail_offset',
        'oca_name',
        'comment',
        'comment_profit',
        'comment_loss',
        'comment_trailing',
        'alert_message',
        'alert_profit',
        'alert_loss',
        'alert_trailing',
        'disable_alert',
      ],
      minArgs: 1,
      maxArgs: 21,
    },
    'strategy.order': { params: ['id', 'direction', 'qty', 'limit', 'stop', 'oca_name', 'oca_type', 'comment', 'alert_message', 'disable_alert'], minArgs: 2, maxArgs: 10 },
    'strategy.risk.allow_entry_in': { params: ['value'], minArgs: 1, maxArgs: 1 },
    'strategy.risk.max_cons_loss_days': { params: ['count', 'alert_message'], minArgs: 1, maxArgs: 2 },
    'strategy.risk.max_drawdown': { params: ['value', 'type', 'alert_message'], minArgs: 2, maxArgs: 3 },
    'strategy.risk.max_intraday_filled_orders': { params: ['count', 'alert_message'], minArgs: 1, maxArgs: 2 },
    'strategy.risk.max_intraday_loss': { params: ['value', 'type', 'alert_message'], minArgs: 2, maxArgs: 3 },
    'strategy.risk.max_position_size': { params: ['contracts'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.commission': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.entry_bar_index': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.entry_comment': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.entry_id': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.entry_price': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.entry_time': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.exit_bar_index': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.exit_comment': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.exit_id': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.exit_price': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.exit_time': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.max_drawdown': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.max_drawdown_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.max_runup': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.max_runup_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.profit': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.profit_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.closedtrades.size': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.commission': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.entry_bar_index': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.entry_comment': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.entry_id': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.entry_price': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.entry_time': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.max_drawdown': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.max_drawdown_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.max_runup': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.max_runup_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.profit': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.profit_percent': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
    'strategy.opentrades.size': { params: ['trade_num'], minArgs: 1, maxArgs: 1 },
  },
} as const satisfies Record<string, Record<string, PineV6ReferenceSignature>>;

export const PINE_V6_KNOWN_MISSING_SIGNATURES = [] as const;

export const PINE_V6_SIGNATURELESS_BUILTINS = [
  'ta.accdist',
  'ta.iii',
  'ta.nvi',
  'ta.pvi',
  'ta.pvt',
  'ta.wad',
  'ta.wvad',
  'math.e',
  'math.phi',
  'math.pi',
  'math.rphi',
  'timeframe.isdaily',
  'timeframe.isdwm',
  'timeframe.isintraday',
  'timeframe.isminutes',
  'timeframe.ismonthly',
  'timeframe.isseconds',
  'timeframe.isticks',
  'timeframe.isweekly',
  'timeframe.main_period',
  'timeframe.multiplier',
  'timeframe.period',
  'session.extended',
  'session.isfirstbar',
  'session.isfirstbar_regular',
  'session.islastbar',
  'session.islastbar_regular',
  'session.ismarket',
  'session.ispostmarket',
  'session.ispremarket',
  'session.regular',
  'syminfo.basecurrency',
  'syminfo.country',
  'syminfo.currency',
  'syminfo.current_contract',
  'syminfo.description',
  'syminfo.employees',
  'syminfo.exchange',
  'syminfo.expiration_date',
  'syminfo.industry',
  'syminfo.isin',
  'syminfo.main_tickerid',
  'syminfo.mincontract',
  'syminfo.minmove',
  'syminfo.mintick',
  'syminfo.pointvalue',
  'syminfo.prefix',
  'syminfo.pricescale',
  'syminfo.recommendations_date',
  'syminfo.root',
  'syminfo.sector',
  'syminfo.session',
  'syminfo.shareholders',
  'syminfo.shares_outstanding_float',
  'syminfo.shares_outstanding_total',
  'syminfo.target_price_average',
  'syminfo.target_price_date',
  'syminfo.target_price_estimates',
  'syminfo.target_price_high',
  'syminfo.target_price_low',
  'syminfo.target_price_median',
  'syminfo.ticker',
  'syminfo.tickerid',
  'syminfo.timezone',
  'syminfo.type',
  'syminfo.volumetype',
  'chart.bg_color',
  'chart.fg_color',
  'chart.is_heikinashi',
  'chart.is_kagi',
  'chart.is_linebreak',
  'chart.is_pnf',
  'chart.is_range',
  'chart.is_renko',
  'chart.is_standard',
  'chart.left_visible_bar_time',
  'chart.right_visible_bar_time',
  'color.aqua',
  'color.black',
  'color.blue',
  'color.fuchsia',
  'color.gray',
  'color.green',
  'color.lime',
  'color.maroon',
  'color.navy',
  'color.none',
  'color.olive',
  'color.orange',
  'color.purple',
  'color.red',
  'color.silver',
  'color.teal',
  'color.white',
  'color.yellow',
  'strategy.account_currency',
  'strategy.avg_losing_trade',
  'strategy.avg_losing_trade_percent',
  'strategy.avg_trade',
  'strategy.avg_trade_percent',
  'strategy.avg_winning_trade',
  'strategy.avg_winning_trade_percent',
  'strategy.cash',
  'strategy.closedtrades',
  'strategy.closedtrades.first_index',
  'strategy.commission.cash_per_contract',
  'strategy.commission.cash_per_order',
  'strategy.commission.percent',
  'strategy.direction.all',
  'strategy.direction.long',
  'strategy.direction.short',
  'strategy.equity',
  'strategy.eventrades',
  'strategy.fixed',
  'strategy.grossloss',
  'strategy.grossloss_percent',
  'strategy.grossprofit',
  'strategy.grossprofit_percent',
  'strategy.initial_capital',
  'strategy.long',
  'strategy.losstrades',
  'strategy.margin_liquidation_price',
  'strategy.max_contracts_held_all',
  'strategy.max_contracts_held_long',
  'strategy.max_contracts_held_short',
  'strategy.max_drawdown',
  'strategy.max_drawdown_percent',
  'strategy.max_runup',
  'strategy.max_runup_percent',
  'strategy.netprofit',
  'strategy.netprofit_percent',
  'strategy.oca.cancel',
  'strategy.oca.none',
  'strategy.oca.reduce',
  'strategy.openprofit',
  'strategy.openprofit_percent',
  'strategy.opentrades',
  'strategy.opentrades.capital_held',
  'strategy.percent_of_equity',
  'strategy.percent_profitable',
  'strategy.position_avg_price',
  'strategy.position_entry_name',
  'strategy.position_size',
  'strategy.short',
  'strategy.wintrades',
] as const;
