/**
 * @tealstreet/tealchart
 * Custom OHLCV candlestick chart with TradingView-compatible API
 */

// Main widget class and factory
export { TealchartWidget, createTealchartWidget } from './TealchartWidget';

// Per-chart API
export { TealchartApi } from './TealchartApi';

export {
  DEFAULT_BUY_CANDLE_COLOR,
  DEFAULT_SELL_CANDLE_COLOR,
  DEFAULT_TRADE_LINE_COLOR,
  POSITIVE_PNL_COLOR,
  STOP_LOSS_COLOR,
  TAKE_PROFIT_COLOR,
} from './constants';

// React Native Skia component - import from '@tealstreet/tealchart/native' for React Native
// NOT exported here to avoid breaking web builds with RN dependencies

// Chart API context (for accessing chartApi in custom components)
export { ChartApiContext, useChartApi, useChartApiOptional } from './state/ChartApiContext';

// Jotai state management (for per-chart persistent settings)
export {
  getChartSettingsAtom,
  createChartFocusAtoms,
  createIntervalMsAtom,
  resolutionToMs,
  getResolutionLabel,
  getDecimalPlacesFromPrecision,
  formatPriceWithPrecision,
  AVAILABLE_TIMEFRAMES,
  DEFAULT_CHART_SETTINGS,
} from './state/chartState';
export type { ChartSettings, TimeframeOption, IndicatorInstance } from './state/chartState';

// Indicator CRUD actions
export {
  createAddIndicatorAtom,
  createRemoveIndicatorAtom,
  createUpdateIndicatorInputsAtom,
  createToggleIndicatorVisibilityAtom,
  createUpdateIndicatorNameAtom,
  createIndicatorActionsAtoms,
  generateIndicatorId,
} from './state/indicatorActions';

// Safe deep merge utilities
export { safeDeepMerge, migrateChartSettings, CHART_SETTINGS_VERSION } from './state/safeDeepMerge';

// User drawing model (platform-neutral)
export {
  anchorToScreenPoint,
  addUserDrawing,
  beginUserDrawingTextEdit,
  createUserDrawingFromDraft,
  DEFAULT_USER_DRAWING_BARS_PATTERN_DISPLAY_MODE,
  DEFAULT_USER_DRAWING_BARS_PATTERN_DOWN_COLOR,
  DEFAULT_USER_DRAWING_BARS_PATTERN_UP_COLOR,
  DEFAULT_USER_DRAWING_MEASUREMENT_LABEL_ALIGNMENT,
  DEFAULT_USER_DRAWING_MEASUREMENT_LABEL_POSITION,
  DEFAULT_USER_DRAWING_RISK_REWARD_LABEL_ALIGNMENT,
  DEFAULT_USER_DRAWING_RISK_REWARD_STATS_MODE,
  DEFAULT_USER_DRAWING_STATE,
  DEFAULT_USER_DRAWING_STYLE,
  DEFAULT_USER_DRAWING_VOLUME_PROFILE_ROW_COUNT,
  DEFAULT_USER_DRAWING_VOLUME_PROFILE_VALUE_AREA_RATIO,
  DEFAULT_USER_DRAWING_VOLUME_PROFILE_WIDTH_RATIO,
  DEFAULT_USER_DRAWING_ICON_NAME,
  DEFAULT_USER_DRAWING_ICON_SIZE,
  DEFAULT_USER_DRAWING_TEXT_LABEL_PADDING,
  DEFAULT_USER_DRAWING_TEXT_LINE_HEIGHT,
  distanceBetweenPoints,
  distanceToRectEdge,
  distanceToSegment,
  drawingXToTime,
  drawingYToPrice,
  cancelUserDrawingDraft,
  cancelUserDrawingTextEdit,
  clearUserDrawings,
  commitUserDrawingTextEdit,
  createUserDrawingClipboard,
  createUserDrawingCommandEvent,
  createUserDrawingHistoryCommandEvent,
  createUserDrawingReplaceStateCommandEvent,
  createUserDrawingState,
  deleteUserDrawing,
  getRequiredAnchorCount,
  getUserDrawingTextAnnotationPoint,
  getUserDrawingPaneId,
  handleUserDrawingInput,
  hitTestUserDrawing,
  hitTestUserDrawings,
  isDrawingDraftReady,
  isUserDrawingPathFamilyTool,
  isUserDrawingTextAnnotation,
  deserializeUserDrawingStateFromLayout,
  isUserDrawingLayoutStateEqual,
  normalizeUserDrawingBarsPatternDisplayMode,
  normalizeUserDrawingFontFamily,
  normalizeUserDrawingMeasurementLabelAlignment,
  normalizeUserDrawingMeasurementLabelPosition,
  normalizeUserDrawingOpacity,
  normalizeUserDrawingRiskRewardLabelAlignment,
  normalizeUserDrawingRiskRewardStatsMode,
  normalizeUserDrawingTableCells,
  normalizeUserDrawingVolumeProfileRowCount,
  normalizeUserDrawingVolumeProfileValueAreaRatio,
  normalizeUserDrawingVolumeProfileWidthRatio,
  FIB_CHANNEL_LEVELS,
  FIB_CIRCLE_LEVELS,
  FIB_FAN_LEVELS,
  FIB_SPEED_RESISTANCE_ARC_LEVELS,
  FIB_SPEED_RESISTANCE_FAN_LEVELS,
  FIB_TIME_ZONE_LEVELS,
  CYCLIC_LINES_MAX_VISIBLE_LEVELS,
  TIME_CYCLES_MAX_VISIBLE_CYCLES,
  TIME_CYCLES_POINTS_PER_CYCLE,
  SINE_LINE_MAX_VISIBLE_POINTS,
  SINE_LINE_POINTS_PER_CYCLE,
  FIB_WEDGE_LEVELS,
  FIB_SPIRAL_GROWTH,
  FIB_SPIRAL_SEGMENTS_PER_TURN,
  FIB_SPIRAL_STEPS,
  FIB_SPIRAL_TURNS,
  GANN_FAN_LEVELS,
  GANN_BOX_LEVELS,
  PITCHFAN_LEVELS,
  priceToDrawingY,
  resolveAnchoredVolumeProfileFromAnchor,
  resolveAnchoredVwapFromAnchor,
  resolveArcFromAnchors,
  resolveBarsPatternFromAnchors,
  resolveCircleFromAnchors,
  resolveCurveFromAnchors,
  resolveDateRangeRectFromAnchors,
  resolveDisjointChannelFromAnchors,
  resolveEllipseFromAnchors,
  resolveFibCirclesFromAnchors,
  resolveFibChannelFromAnchors,
  resolveFibFanFromAnchors,
  resolveFibSpeedResistanceArcsFromAnchors,
  resolveFibSpeedResistanceFanFromAnchors,
  resolveFibTimeZoneFromAnchors,
  resolveCyclicLinesFromAnchors,
  resolveTimeCyclesFromAnchors,
  resolveSineLineFromAnchors,
  resolveForecastFromAnchors,
  resolveProjectionFromAnchors,
  resolveSectorFromAnchors,
  resolveTableFromAnchor,
  resolveAbcdPatternFromAnchors,
  resolveElliottCorrectiveWaveFromAnchors,
  resolveElliottImpulseWaveFromAnchors,
  resolveElliottTriangleWaveFromAnchors,
  resolveHeadShouldersPatternFromAnchors,
  resolveTrianglePatternFromAnchors,
  resolveThreeDrivesPatternFromAnchors,
  resolveXabcdPatternFromAnchors,
  resolveFibWedgeFromAnchors,
  resolveFibSpiralFromAnchors,
  resolveTrendBasedFibTimeFromAnchors,
  resolveFlatTopBottomFromAnchors,
  resolveGannBoxFromAnchors,
  resolveGannFanFromAnchors,
  resolveGannSquareFromAnchors,
  resolvePitchforkFromAnchors,
  resolvePitchfanFromAnchors,
  resolvePolylineFromAnchors,
  resolveParallelChannelFromAnchors,
  resolveRegressionTrendFromAnchors,
  resolveRiskRewardPositionFromAnchors,
  resolveUserDrawingDateRangeMetrics,
  resolveUserDrawingInfoLineMetrics,
  resolveExtendedSegment,
  resolveRaySegment,
  resolveRectFromAnchors,
  resolveRotatedRectangleFromAnchors,
  resolveTrendAngleFromSegment,
  resolveUserDrawingHandlePoints,
  resolveUserDrawingGeometry,
  resolveUserDrawingIconGeometry,
  resolveUserDrawingInputPoint,
  resolveUserDrawingInputPointFromChart,
  resolveUserDrawingPriceRangeMetrics,
  resolveUserDrawingRenderEntries,
  resolveUserDrawingRiskRewardMetrics,
  resolveUserDrawingBalloonLayout,
  resolveUserDrawingTextEditMetrics,
  resolveUserDrawingTextLabelLayout,
  resolveUserDrawingVisualPriceRangeMetrics,
  deleteUserDrawingTableColumn,
  deleteUserDrawingTableRow,
  duplicateUserDrawing,
  getUserDrawingSelectionIds,
  getUserDrawingBrushTemplateDescriptors,
  insertUserDrawingTableColumn,
  insertUserDrawingTableRow,
  pasteUserDrawingClipboard,
  selectUserDrawing,
  selectUserDrawingById,
  selectUserDrawingsById,
  getUserDrawingToolbarStateKey,
  getUserDrawingToolDescriptor,
  getUserDrawingZOrderAction,
  isUserDrawingIconToolbarEnabled,
  isUserDrawingToolbarActionEnabled,
  normalizeUserDrawingFontWeight,
  normalizeUserDrawingFontStyle,
  normalizeUserDrawingIconName,
  normalizeUserDrawingTextMaxWidth,
  renderUserDrawing,
  renderUserDrawingLayer,
  renderUserDrawings,
  reorderUserDrawings,
  resolveUserDrawingEditIntentAtPoint,
  resolveUserDrawingObjectTreeActionCommands,
  resolveUserDrawingObjectTreeDrawingDispatchAction,
  resolveUserDrawingObjectTreeModel,
  resolveUserDrawingObjectTreeRowDispatchAction,
  resolveUserDrawingObjectTreeSelectionDispatchAction,
  resolveUserDrawingPropertiesIntent,
  resolveUserDrawingPropertiesSurface,
  resolveUserDrawingPropertiesSurfaceCommand,
  createUserDrawingVisualEvidencePrNoteTemplate,
  resolveUserDrawingKeyboardAction,
  nudgeUserDrawingSelection,
  screenPointToAnchor,
  setUserDrawingIconName,
  setUserDrawingImageSource,
  setUserDrawingLocked,
  setUserDrawingName,
  setUserDrawingTableCell,
  setUserDrawingTableCells,
  setUserDrawingTableDimensions,
  setUserDrawingText,
  setUserDrawingTextContent,
  setUserDrawingTextAlign,
  setUserDrawingTrendLineExtend,
  setUserDrawingTool,
  setUserDrawingVisibility,
  serializeUserDrawingStateForLayout,
  measureUserDrawingTextLines,
  splitUserDrawingTextLines,
  timeToDrawingX,
  updateUserDrawingStyle,
  updateUserDrawingTextEdit,
  USER_DRAWING_BARS_PATTERN_DOWN_COLOR_DESCRIPTORS,
  USER_DRAWING_BARS_PATTERN_DISPLAY_MODE_DESCRIPTORS,
  USER_DRAWING_BARS_PATTERN_DISPLAY_MODES,
  USER_DRAWING_BARS_PATTERN_UP_COLOR_DESCRIPTORS,
  USER_DRAWING_BRUSH_TEMPLATE_DESCRIPTORS,
  USER_DRAWING_FONT_FAMILIES,
  USER_DRAWING_FONT_FAMILY_DESCRIPTORS,
  USER_DRAWING_FONT_STYLE_DESCRIPTORS,
  USER_DRAWING_FONT_STYLES,
  USER_DRAWING_VISUAL_EVIDENCE_MATRIX,
  USER_DRAWING_FONT_WEIGHT_DESCRIPTORS,
  USER_DRAWING_FONT_WEIGHTS,
  USER_DRAWING_ICON_NAMES,
  USER_DRAWING_ICON_NAME_DESCRIPTORS,
  USER_DRAWING_MEASUREMENT_LABEL_ALIGNMENT_DESCRIPTORS,
  USER_DRAWING_MEASUREMENT_LABEL_ALIGNMENTS,
  USER_DRAWING_MEASUREMENT_LABEL_POSITION_DESCRIPTORS,
  USER_DRAWING_MEASUREMENT_LABEL_POSITIONS,
  USER_DRAWING_OPACITY_DESCRIPTORS,
  USER_DRAWING_RISK_REWARD_LABEL_ALIGNMENT_DESCRIPTORS,
  USER_DRAWING_RISK_REWARD_LABEL_ALIGNMENTS,
  USER_DRAWING_RISK_REWARD_STATS_MODE_DESCRIPTORS,
  USER_DRAWING_RISK_REWARD_STATS_MODES,
  USER_DRAWING_STYLE_TOGGLE_DESCRIPTORS,
  USER_DRAWING_TEXT_DECORATION_DESCRIPTORS,
  USER_DRAWING_TEXT_MAX_WIDTH_DESCRIPTORS,
  USER_DRAWING_TEXT_MAX_WIDTHS,
  USER_DRAWING_TEXT_WRAP_DESCRIPTORS,
  USER_DRAWING_TREND_LINE_EXTEND_DESCRIPTORS,
  USER_DRAWING_TREND_LINE_EXTENDS,
  USER_DRAWING_VOLUME_PROFILE_ROW_COUNT_DESCRIPTORS,
  USER_DRAWING_VOLUME_PROFILE_ROW_COUNTS,
  USER_DRAWING_VOLUME_PROFILE_VALUE_AREA_RATIO_DESCRIPTORS,
  USER_DRAWING_VOLUME_PROFILE_VALUE_AREA_RATIOS,
  USER_DRAWING_VOLUME_PROFILE_WIDTH_RATIO_DESCRIPTORS,
  USER_DRAWING_VOLUME_PROFILE_WIDTH_RATIOS,
  USER_DRAWING_TOOL_DESCRIPTORS,
  USER_DRAWING_TOOLBAR_ACTION_DESCRIPTORS,
  supportsUserDrawingTextAlignControls,
  supportsUserDrawingTextControls,
  supportsUserDrawingTextStyleControls,
  supportsUserDrawingTextWrapControls,
  supportsUserDrawingTrendLineExtendControls,
  supportsUserDrawingBarsPatternColorControls,
  supportsUserDrawingBarsPatternDisplayModeControls,
  supportsUserDrawingMeasurementLabelPositionControls,
  supportsUserDrawingRiskRewardLabelAlignmentControls,
  supportsUserDrawingRiskRewardStatsModeControls,
  supportsUserDrawingVolumeProfileRowCountControls,
  supportsUserDrawingVolumeProfileValueAreaControls,
  supportsUserDrawingVolumeProfileWidthControls,
  USER_DRAWING_OPACITIES,
  USER_DRAWING_SCHEMA_VERSION,
  formatUserDrawingDateRangeBars,
  formatUserDrawingDateRangeDuration,
  formatTrendAngleDegrees,
  ABCD_PATTERN_LABELS,
  ELLIOTT_CORRECTIVE_WAVE_LABELS,
  ELLIOTT_IMPULSE_WAVE_LABELS,
  ELLIOTT_TRIANGLE_WAVE_LABELS,
  HEAD_SHOULDERS_PATTERN_LABELS,
  THREE_DRIVES_PATTERN_LABELS,
  TRIANGLE_PATTERN_LABELS,
  XABCD_PATTERN_LABELS,
} from './drawings';
export type {
  AbcdPatternDrawing,
  AbcdPatternLabel,
  CreateUserDrawingFromDraftOptions,
  AnchoredVolumeProfileDrawing,
  AnchoredVwapDrawing,
  ArcDrawing,
  ArrowLineDrawing,
  ArrowMarkDownDrawing,
  ArrowMarkUpDrawing,
  ArrowMarkerDrawing,
  BalloonDrawing,
  BarsPatternBarSnapshot,
  CircleDrawing,
  CyclicLinesDrawing,
  DatePriceRangeDrawing,
  DateRangeDrawing,
  CopyUserDrawingOptions,
  DeleteUserDrawingOptions,
  DuplicateUserDrawingOptions,
  DisjointChannelDrawing,
  CurveDrawing,
  CrossLineDrawing,
  EllipseDrawing,
  ExtendedLineDrawing,
  FibChannelDrawing,
  FibCirclesDrawing,
  FibFanDrawing,
  FibSpeedResistanceArcsDrawing,
  FibSpeedResistanceFanDrawing,
  FibTimeZoneDrawing,
  FibWedgeDrawing,
  FibSpiralDrawing,
  TrendBasedFibTimeDrawing,
  GannBoxDrawing,
  GannFanDrawing,
  GannSquareDrawing,
  GannSquareFixedDrawing,
  DrawingCoordinateSpace,
  DrawingPitchforkVariant,
  DrawingScreenAbcdPattern,
  DrawingScreenAbcdPatternLabel,
  DrawingScreenAnchoredVwap,
  DrawingScreenArc,
  DrawingScreenBarsPattern,
  DrawingScreenBarsPatternBar,
  DrawingScreenCyclicLineLevel,
  DrawingScreenCyclicLines,
  DrawingScreenPoint,
  DrawingScreenSineLine,
  DrawingScreenTimeCycle,
  DrawingScreenTimeCycles,
  DrawingScreenCircle,
  DrawingScreenCrossLine,
  DrawingScreenCurve,
  DrawingScreenEllipse,
  DrawingScreenFibArc,
  DrawingScreenFibSpeedResistanceArcs,
  DrawingScreenFibWedge,
  DrawingScreenFibSpiral,
  DrawingScreenFibCircle,
  DrawingScreenFibCircles,
  DrawingScreenFibChannel,
  DrawingScreenFibTimeZone,
  DrawingScreenFibTimeZoneLevel,
  DrawingScreenFibChannelLevel,
  DrawingScreenFibFan,
  DrawingScreenFixedRangeVolumeProfile,
  DrawingScreenVolumeProfileBin,
  DrawingScreenVolumeProfileGuide,
  DrawingScreenVolumeProfileGuideKind,
  DrawingScreenGannBox,
  DrawingScreenGannBoxLevel,
  DrawingScreenForecast,
  DrawingScreenGannFan,
  DrawingScreenProjection,
  DrawingScreenSector,
  DrawingScreenParallelChannel,
  DrawingScreenPitchfork,
  DrawingScreenPitchfan,
  DrawingScreenPitchfanRay,
  DrawingScreenPolyline,
  DrawingScreenRect,
  DrawingScreenRiskRewardPosition,
  DrawingScreenSegment,
  DrawingScreenTable,
  DrawingScreenTableCell,
  DrawingScreenTrendAngle,
  DrawingScreenElliottCorrectiveWave,
  DrawingScreenElliottCorrectiveWaveLabel,
  DrawingScreenElliottImpulseWave,
  DrawingScreenElliottImpulseWaveLabel,
  DrawingScreenElliottTriangleWave,
  DrawingScreenElliottTriangleWaveLabel,
  DrawingScreenHeadShouldersPattern,
  DrawingScreenHeadShouldersPatternLabel,
  DrawingScreenThreeDrivesPattern,
  DrawingScreenThreeDrivesPatternLabel,
  DrawingScreenTrianglePattern,
  DrawingScreenTrianglePatternLabel,
  DrawingScreenXabcdPattern,
  DrawingScreenXabcdPatternLabel,
  FlatTopBottomDrawing,
  HorizontalLineDrawing,
  HorizontalRayDrawing,
  InfoLineDrawing,
  LongPositionDrawing,
  PathDrawing,
  ParallelChannelDrawing,
  PitchforkDrawing,
  PitchforkDrawingKind,
  PitchfanDrawing,
  PinDrawing,
  PriceNoteDrawing,
  PriceRangeDrawing,
  RayDrawing,
  RectangleDrawing,
  RegressionTrendDrawing,
  RotatedRectangleDrawing,
  ResolveUserDrawingBalloonLayoutOptions,
  ResolveUserDrawingInputFromChartOptions,
  ResolveUserDrawingIconGeometryOptions,
  ResolveUserDrawingInputPointOptions,
  ResolveUserDrawingRenderEntriesOptions,
  ResolveUserDrawingTextLabelLayoutOptions,
  ResolvedUserDrawingGeometry,
  TextLabelDrawing,
  ElliottCorrectiveWaveDrawing,
  ElliottCorrectiveWaveLabel,
  ElliottImpulseWaveDrawing,
  ElliottImpulseWaveLabel,
  ElliottTriangleWaveDrawing,
  ElliottTriangleWaveLabel,
  HeadShouldersPatternDrawing,
  HeadShouldersPatternLabel,
  ThreeDrivesPatternDrawing,
  ThreeDrivesPatternLabel,
  NoteDrawing,
  CalloutDrawing,
  CommentDrawing,
  TimeCyclesDrawing,
  TriangleDrawing,
  TrianglePatternDrawing,
  TrianglePatternLabel,
  TrendAngleDrawing,
  TrendLineDrawing,
  UserDrawing,
  UserDrawingAnchor,
  UserDrawingBalloonLayout,
  UserDrawingBase,
  UserDrawingDateRangeMetrics,
  UserDrawingInfoLineMetrics,
  UserDrawingDraft,
  UserDrawingHandleRole,
  UserDrawingIconGeometry,
  UserDrawingIconName,
  UserDrawingIconNameDescriptor,
  UserDrawingKind,
  UserDrawingFontFamily,
  UserDrawingFontSize,
  UserDrawingFontFamilyDescriptor,
  UserDrawingFontStyle,
  UserDrawingFontStyleDescriptor,
  UserDrawingFontWeight,
  UserDrawingFontWeightDescriptor,
  UserDrawingLineStyle,
  UserDrawingMagnetMode,
  UserDrawingMeasuredTextLine,
  UserDrawingOpacityDescriptor,
  UserDrawingBrushTemplateDescriptor,
  UserDrawingBrushTemplateId,
  ResolveUserDrawingObjectTreeRowDispatchActionOptions,
  ResolveUserDrawingEditIntentOptions,
  ResolveUserDrawingPropertiesIntentOptions,
  UserDrawingEditIntent,
  UserDrawingEditIntentKind,
  UserDrawingObjectTreeAction,
  UserDrawingObjectTreeCommandOptions,
  UserDrawingObjectTreeGroup,
  UserDrawingObjectTreeModel,
  UserDrawingObjectTreeMutationAction,
  UserDrawingObjectTreeOptions,
  UserDrawingObjectTreeOrder,
  UserDrawingObjectTreeRow,
  UserDrawingObjectTreeRowAction,
  UserDrawingObjectTreeRowActionType,
  UserDrawingObjectTreeSelectionActionDescriptor,
  UserDrawingObjectTreeSelectionActionType,
  UserDrawingPropertiesIntent,
  ResolveUserDrawingPropertiesSurfaceCommandOptions,
  UserDrawingPropertiesSurface,
  UserDrawingPropertiesSurfaceCommand,
  UserDrawingPropertiesSurfaceControl,
  UserDrawingPropertiesSurfaceGroup,
  UserDrawingVisualEvidenceMatrix,
  UserDrawingVisualEvidenceState,
  UserDrawingVisualEvidenceStateId,
  UserDrawingVisualEvidenceStateStatus,
  UserDrawingVisualEvidenceViewport,
  UserDrawingVisualEvidenceViewportId,
  UserDrawingObjectTreeSelectionAction,
  UserDrawingBarsPatternColorDescriptor,
  UserDrawingBarsPatternDisplayMode,
  UserDrawingBarsPatternDisplayModeDescriptor,
  UserDrawingMeasurementLabelAlignment,
  UserDrawingMeasurementLabelAlignmentDescriptor,
  UserDrawingMeasurementLabelPosition,
  UserDrawingMeasurementLabelPositionDescriptor,
  UserDrawingPriceRangeMetrics,
  UserDrawingRiskRewardLabelAlignment,
  UserDrawingRiskRewardLabelAlignmentDescriptor,
  UserDrawingRiskRewardMetrics,
  UserDrawingRiskRewardStatsMode,
  UserDrawingRiskRewardStatsModeDescriptor,
  UserDrawingSelection,
  UserDrawingState,
  UserDrawingStyle,
  UserDrawingStyleToggleDescriptor,
  UserDrawingTextAlign,
  UserDrawingTextDecorationDescriptor,
  UserDrawingTextMaxWidth,
  UserDrawingTextMaxWidthDescriptor,
  UserDrawingTextWrapDescriptor,
  UserDrawingVolumeProfileRowCount,
  UserDrawingVolumeProfileRowCountDescriptor,
  UserDrawingVolumeProfileValueAreaRatio,
  UserDrawingVolumeProfileValueAreaRatioDescriptor,
  UserDrawingVolumeProfileWidthRatio,
  UserDrawingVolumeProfileWidthRatioDescriptor,
  UserDrawingTrendLineExtend,
  UserDrawingTrendLineExtendDescriptor,
  UserDrawingHitResult,
  UserDrawingHitTestOptions,
  UserDrawingHitTestTextMeasure,
  UserDrawingClipboard,
  AddUserDrawingOptions,
  UserDrawingCommand,
  UserDrawingCommandDispatchResult,
  UserDrawingCommandEvent,
  UserDrawingCommandEventCommand,
  UserDrawingCommandEventListener,
  UserDrawingHistoryCommand,
  UserDrawingReplaceStateCommand,
  UserDrawingCommandAvailability,
  UserDrawingCommandMetadata,
  UserDrawingCommandSource,
  UserDrawingInputOptions,
  UserDrawingInputPoint,
  NudgeUserDrawingSelectionOptions,
  PasteUserDrawingOptions,
  UserDrawingRenderOptions,
  UserDrawingRenderEntry,
  UserDrawingRenderPhase,
  UserDrawingTextEditMetrics,
  UserDrawingTextLabelLayout,
  UserDrawingTextLineLayout,
  UserDrawingTextEdit,
  UserDrawingTextEditOptions,
  UserDrawingImageSourceInput,
  UserDrawingKeyboardAction,
  UserDrawingKeyboardActionType,
  UserDrawingKeyboardFocusOwner,
  UserDrawingKeyboardInput,
  UserDrawingTableCellInput,
  UserDrawingTableCellsInput,
  UserDrawingTableColumnInput,
  UserDrawingTableRowInput,
  UserDrawingToolbarAction,
  UserDrawingToolbarActionDescriptor,
  UserDrawingToolDescriptor,
  UserDrawingTool,
  UserDrawingZOrderAction,
  UserDrawingPathFamilyKind,
  UserDrawingTextAnnotation,
  UserDrawingTextAnnotationKind,
  BarsPatternDrawing,
  BrushDrawing,
  ForecastDrawing,
  HighlighterDrawing,
  IconDrawing,
  ProjectionDrawing,
  SectorDrawing,
  ShortPositionDrawing,
  SineLineDrawing,
  TableDrawing,
  UpdateUserDrawingOptions,
  VerticalLineDrawing,
  XabcdPatternDrawing,
  XabcdPatternLabel,
} from './drawings';

// Gap detection (for advanced usage)
export { GapDetectionManager } from './GapDetectionManager';

// Debug logging
export { TealchartLogger, LogLevel, LogCategory } from './debug';
export type { LogEntry, LogCategoryType, TealchartLoggerOptions } from './debug';
// Event system
export { EventEmitter, Subscription } from './events/EventEmitter';
export type { EventCallback } from './events/EventEmitter';

// Types
export type {
  // Core chart types
  Bar,
  Viewport,
  RenderOptions,
  ChartOverrides,
  ChartMargins,
  InteractionState,
  CrosshairState,
  DragMode,
  // Price line system
  PriceLine,
  PriceLineLabel,
  PriceLineLabelBounds,
  // TradingView-compatible types
  WidgetEvent,
  WidgetEventCallback,
  WidgetEventMap,
  ResolutionString,
  CrossHairMovedEventParams,
  EnhancedCrossHairState,
  ISubscription,
  ContextMenuItem,
  ContextMenuCallback,
  ITimeScaleApi,
  // Order/Position line types
  ExecutionDirection,
  IExecutionLineAdapter,
  OrderLineOptions,
  IOrderLineAdapter,
  TealstreetOrderLineExtensions,
  FullOrderLineAdapter,
  PositionLineOptions,
  IPositionLineAdapter,
  TealstreetPositionLineExtensions,
  FullPositionLineAdapter,
  // Study types
  StudyInfo,
  IStudyApi,
  // Datafeed types
  IBasicDataFeed,
  DatafeedConfiguration,
  LibrarySymbolInfo,
  PeriodParams,
  // Widget options
  TealchartWidgetOptions,
  // Gap detection types
  GapDetectionOptions,
  GapDetectionEvent,
  GapDetectionReason,
} from './types';

// Default values
export { DEFAULT_RENDER_OPTIONS, DEFAULT_MARGINS } from './types';

// Cross-platform chart themes
export {
  BUILTIN_CHART_THEMES,
  DARK_CHART_THEME,
  LIGHT_CHART_THEME,
  chartThemeToRenderOptions,
  mergeChartThemeRenderOptions,
  resolveChartTheme,
} from './theme';
export type { ChartTheme, ChartThemeInput, ChartThemeName, ChartThemeRenderOptions } from './theme';

// Tealscript integration
export {
  TealscriptManager,
  useTealscript,
  type TealscriptManagerOptions,
  type UseTealscriptOptions,
  type UseTealscriptReturn,
} from './tealscript';
export type {
  PlotOutput,
  PlotStyle,
  AlertEvent,
  AlertFrequency,
  AlertOutput,
  DrawingOutput,
  LabelDrawingOutput,
  InputDefinition,
  TealscriptBar,
  WorkerResult,
  WorkerError,
} from './tealscript';

// Built-in indicators
export {
  BUILTIN_INDICATORS,
  INDICATOR_CATEGORIES,
  getIndicatorsByCategory,
  getIndicatorById,
  searchIndicators,
} from './indicators';
export type { BuiltinIndicator } from './indicators';

// Pane management (for multi-pane indicator rendering)
export { PaneManager } from './rendering/PaneManager';
export type { PaneOffset, AddIndicatorOptions } from './rendering/PaneManager';
export type { IndicatorPane, PaneLayout } from './types';
export { DEFAULT_PANE_LAYOUT, DEFAULT_INDICATOR_PANE_HEIGHT, MIN_PANE_HEIGHT } from './types';

// Shared chart layout geometry
export {
  DEFAULT_CHART_CHROME_LAYOUT,
  EMPTY_INSETS,
  MOBILE_CHART_CHROME_METRICS,
  WEB_CHART_CHROME_METRICS,
  clampRectToBounds,
  computeChartGeometry,
  computeLeftToolRailTop,
  computePaneGeometry,
  computeTopLeftLegendRect,
  insetRect,
  intersectsRect,
  normalizeInsets,
  rect,
  rectBottom,
  rectRight,
} from './layout/chartGeometry';
export type {
  ChartChromeLayoutModes,
  ChartChromeMetrics,
  ChartChromeRegion,
  ChartGeometryInput,
  ChartGeometrySnapshot,
  ChartLayoutMode,
  Insets,
  Rect,
  TopLeftLegendRectOptions,
} from './layout/chartGeometry';

// TradingView Layout Transformer
// For saving/loading Custom Chart layouts in TradingView format
export {
  // Transform functions
  toTvFormat,
  fromTvFormat,
  // SaveLoad integration
  saveTealchartLayout,
  updateTealchartLayout,
  loadAsTealchart,
  isTealchartLayout,
  getAllLayouts,
  deleteLayout,
  migrateFromLocalStorage,
  // Storage-backed SaveLoad adapter
  StorageSaveLoadAdapter,
  DEFAULT_LAYOUT_STORAGE_NAMESPACE,
  createLocalStorageKeyValueStorage,
  createAsyncStorageKeyValueStorage,
  createLocalStorageSaveLoadAdapter,
  // Indicator mapping utilities
  findMappingByCustomId,
  findMappingByTvStudyId,
  isCustomIdSupported,
  isTvStudyIdSupported,
  INDICATOR_MAPPINGS,
  // Migration utilities
  migrateSettings,
  needsMigration,
  CURRENT_VERSION as TRANSFORMER_CURRENT_VERSION,
} from './transformer';
export type {
  TransformResult,
  TvChartData,
  TvChartContent,
  IndicatorMapping,
  ISaveLoadAdapter,
  LayoutMetadata,
  TealchartKeyValueStorage,
  AsyncStorageLike,
  StorageSaveLoadAdapterOptions,
} from './transformer';

// Internationalization support
export { TranslationProvider, useChartTranslations, getTranslation, DEFAULT_TRANSLATIONS } from './i18n';
export type { ChartTranslations, PartialChartTranslations, TranslationProviderProps } from './i18n';

// Core widget logic (platform-agnostic)
export { ChartWidgetCore, getIntervalMs, INITIAL_BAR_COUNT } from './core';
export type { ChartWidgetCoreOptions, IIndicatorManager } from './core';

// React hook for core widget (works on web and mobile)
export { useTealchartCore } from './core/useTealchartCore';
export type {
  UseTealchartCoreOptions,
  TealchartCoreState,
  TealchartCoreActions,
  UseTealchartCoreReturn,
} from './core/useTealchartCore';
