import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { measureVisualSnapshotDriftFromBuffers } from '../src/rendering/visualSnapshotDrift';
import { VISUAL_SNAPSHOT_DRIFT_BASELINE } from '../src/rendering/visualSnapshotDriftBaseline';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, '..');
const snapshotDir = resolve(packageRoot, 'src/rendering/__visual_snapshots__');
const baselinePath = resolve(packageRoot, 'src/rendering/visualSnapshotDriftBaseline.ts');

async function main(): Promise<void> {
  const files = await readdir(snapshotDir);
  const diffFiles = files.filter((file) => file.endsWith('.diff.png')).sort();
  const measurements: VisualSnapshotDriftBaselineEntry[] = [];

  for (const diffFile of diffFiles) {
    const name = diffFile.slice(0, -'.diff.png'.length);
    const [expected, actual] = await Promise.all([
      readFile(join(snapshotDir, `${name}.png`)),
      readFile(join(snapshotDir, diffFile)),
    ]);
    const measurement = await measureVisualSnapshotDriftFromBuffers(name, expected, actual);
    if (Number.isFinite(measurement.differingPixelRatio)) {
      measurements.push({ ...measurement, platform: process.platform });
    }
  }

  const mergedMeasurements = [
    ...VISUAL_SNAPSHOT_DRIFT_BASELINE.filter((entry) => entry.platform !== process.platform),
    ...measurements,
  ].sort((a, b) => a.platform.localeCompare(b.platform) || a.name.localeCompare(b.name));

  await writeFile(baselinePath, formatBaseline(mergedMeasurements), 'utf8');
  process.stdout.write(
    `Wrote ${measurements.length} ${process.platform} visual snapshot drift entries to ${baselinePath}\n`,
  );
}

interface VisualSnapshotDriftBaselineEntry {
  name: string;
  platform: NodeJS.Platform;
  differingPixels: number;
  totalPixels: number;
  differingPixelRatio: number;
  channelTolerance: number;
  maxDifferingPixelRatio: number;
  width: number;
  height: number;
}

function formatBaseline(measurements: VisualSnapshotDriftBaselineEntry[]): string {
  const entries = measurements
    .map(
      (measurement) => `  {
    name: ${formatStringLiteral(measurement.name)},
    platform: ${formatStringLiteral(measurement.platform)},
    differingPixels: ${measurement.differingPixels},
    totalPixels: ${measurement.totalPixels},
    differingPixelRatio: ${measurement.differingPixelRatio},
    channelTolerance: ${measurement.channelTolerance},
    maxDifferingPixelRatio: ${measurement.maxDifferingPixelRatio},
    width: ${measurement.width},
    height: ${measurement.height},
  }`,
    )
    .join(',\n');

  return `// Generated by \`yarn workspace @tealstreet/tealchart visual:snapshot:drift\`
// after running the visual snapshot tests that produce \`.diff.png\` diagnostics.
// Do not edit by hand. A regeneration that moves these numbers must be
// justified in the commit message, because this file is the per-snapshot ratchet
// that makes tolerated visual drift visible in review.

export interface VisualSnapshotDriftBaselineEntry {
  name: string;
  platform: NodeJS.Platform;
  differingPixels: number;
  totalPixels: number;
  differingPixelRatio: number;
  channelTolerance: number;
  maxDifferingPixelRatio: number;
  width: number;
  height: number;
}

export const VISUAL_SNAPSHOT_DRIFT_BASELINE: VisualSnapshotDriftBaselineEntry[] = [${entries ? `\n${entries},\n` : ''}];
`;
}

function formatStringLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
