/**
 * Generated TealScript parser
 * DO NOT EDIT - Generated by scripts/build-parser.js
 */

import type { Expression, Program, Statement } from './ast';

export type ParseStartRule = 'Program' | 'Expression' | 'Statement';

export type ParseResult<T extends ParseStartRule> =
  T extends 'Expression' ? Expression :
  T extends 'Statement' ? Statement :
  Program;

export interface ParseOptions<T extends ParseStartRule = 'Program'> {
  startRule?: T;
  grammarSource?: string;
}

export interface SyntaxError extends Error {
  location: {
    start: { line: number; column: number; offset: number };
    end: { line: number; column: number; offset: number };
  };
  found: string | null;
  expected: Array<{ type: string; description: string }>;
}

export function parse(input: string, options?: ParseOptions<'Program'>): Program;
export function parse(input: string, options: ParseOptions<'Expression'>): Expression;
export function parse(input: string, options: ParseOptions<'Statement'>): Statement;
export function parse<T extends ParseStartRule>(input: string, options: ParseOptions<T>): ParseResult<T>;
export const SyntaxError: new (message: string, expected: unknown, found: unknown, location: unknown) => SyntaxError;
