/**
 * Generated TealScript parser
 * DO NOT EDIT - Generated by scripts/build-parser.js
 */

import type { Program } from './ast';

export interface ParseOptions {
  startRule?: 'Program' | 'Expression' | 'Statement';
  grammarSource?: string;
}

export interface SyntaxError extends Error {
  location: {
    start: { line: number; column: number; offset: number };
    end: { line: number; column: number; offset: number };
  };
  found: string | null;
  expected: Array<{ type: string; description: string }>;
}

export function parse(input: string, options?: ParseOptions): Program;
export const SyntaxError: new (message: string, expected: unknown, found: unknown, location: unknown) => SyntaxError;
