// Generated by `yarn workspace @tealstreet/tealchart visual:snapshot:drift`
// after running the visual snapshot tests that produce `.diff.png` diagnostics.
// Do not edit by hand. A regeneration that moves these numbers must be
// justified in the commit message, because this file is the per-snapshot ratchet
// that makes tolerated visual drift visible in review.

export interface VisualSnapshotDriftBaselineEntry {
  name: string;
  platform: NodeJS.Platform;
  differingPixels: number;
  totalPixels: number;
  differingPixelRatio: number;
  channelTolerance: number;
  maxDifferingPixelRatio: number;
  width: number;
  height: number;
}

export const VISUAL_SNAPSHOT_DRIFT_BASELINE: VisualSnapshotDriftBaselineEntry[] = [
  {
    name: 'composite-macd',
    platform: 'darwin',
    differingPixels: 4357,
    totalPixels: 120000,
    differingPixelRatio: 0.03630833333333333,
    channelTolerance: 16,
    maxDifferingPixelRatio: 0.08,
    width: 400,
    height: 300,
  },
  {
    name: 'histogram-basic',
    platform: 'darwin',
    differingPixels: 5842,
    totalPixels: 120000,
    differingPixelRatio: 0.048683333333333335,
    channelTolerance: 16,
    maxDifferingPixelRatio: 0.08,
    width: 400,
    height: 300,
  },
];
