#!/usr/bin/env node

/**
 * Build the TealScript parser from the Peggy grammar
 *
 * Usage: node scripts/build-parser.js
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import peggy from 'peggy';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, '..', 'src', 'parser');

const grammarPath = join(srcDir, 'grammar.peggy');
const outputPath = join(srcDir, 'generated.js');
const dtsPath = join(srcDir, 'generated.d.ts');

console.log('Building TealScript parser...');
console.log(`  Grammar: ${grammarPath}`);
console.log(`  Output:  ${outputPath}`);

try {
  // Read grammar
  const grammar = readFileSync(grammarPath, 'utf-8');

  // Generate parser
  const parserSource = peggy.generate(grammar, {
    output: 'source',
    format: 'es',
    allowedStartRules: ['Program', 'Expression', 'Statement'],
  });

  // Write parser
  writeFileSync(outputPath, parserSource, 'utf-8');

  // Write TypeScript declarations
  const dts = `/**
 * Generated TealScript parser
 * DO NOT EDIT - Generated by scripts/build-parser.js
 */

import type { Program } from './ast';

export interface ParseOptions {
  startRule?: 'Program' | 'Expression' | 'Statement';
  grammarSource?: string;
}

export interface SyntaxError extends Error {
  location: {
    start: { line: number; column: number; offset: number };
    end: { line: number; column: number; offset: number };
  };
  found: string | null;
  expected: Array<{ type: string; description: string }>;
}

export function parse(input: string, options?: ParseOptions): Program;
export const SyntaxError: new (message: string, expected: unknown, found: unknown, location: unknown) => SyntaxError;
`;

  writeFileSync(dtsPath, dts, 'utf-8');

  console.log('Parser built successfully!');
} catch (error) {
  console.error('Failed to build parser:', error.message);
  process.exit(1);
}
