import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { MOBILE_TEALSCRIPT_CAPABILITY_BASELINE } from '../../tealchart/src/mobile/mobileTealscriptCapabilityBaseline.ts';
import { PINE_PRODUCTION_WORKER_FALLBACK_BASELINE } from '../src/compat/productionWorkerFallbackBaseline.ts';
import { summarizePineV6ReferenceManualAudit } from '../src/compat/pineV6ReferenceManualAudit.ts';
import { resolvesBuiltinReferenceNameForCoverage } from '../src/semantic/checker.ts';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, '..');

export const PINE_PARITY_HEADLINE_METRICS_START =
  '<!-- BEGIN GENERATED PINE PARITY HEADLINE METRICS';
export const PINE_PARITY_HEADLINE_METRICS_END =
  'END GENERATED PINE PARITY HEADLINE METRICS -->';

export const PINE_PARITY_HEADLINE_METRIC_DOC_PATHS = [
  resolve(packageRoot, 'PINE_PARITY_STATE.md'),
  resolve(packageRoot, 'PINE_PARITY_PR_DESCRIPTION.md'),
] as const;

export function buildPineParityHeadlineMetricsBlock(): string {
  const manualAudit = summarizePineV6ReferenceManualAudit({
    resolvesBuiltinReferenceName: resolvesBuiltinReferenceNameForCoverage,
  });
  const productionBaseline = PINE_PRODUCTION_WORKER_FALLBACK_BASELINE.overall;
  const mobileSupported = MOBILE_TEALSCRIPT_CAPABILITY_BASELINE.filter((row) => row.mobileStatus === 'supported');
  const mobileMissing = MOBILE_TEALSCRIPT_CAPABILITY_BASELINE.filter((row) => row.mobileStatus !== 'supported');

  const resolvedOfficialBuiltins = manualAudit.officialBuiltinNames - manualAudit.unresolvedManualBuiltinNamesCount;
  const coveredGrammarEntries =
    manualAudit.manualGrammarEntries - manualAudit.grammarEntriesAbsentFromCommittedListCount;

  return [
    PINE_PARITY_HEADLINE_METRICS_START,
    'Generated by `yarn workspace @tealstreet/tealscript pine:parity:metrics`.',
    'Do not edit this block by hand; rerun the generator when committed audit or baseline data changes.',
    '-->',
    '',
    `- Pine v6 builtin names: ${resolvedOfficialBuiltins}/${manualAudit.officialBuiltinNames} official manual names implemented/resolved; ${manualAudit.unresolvedManualBuiltinNamesCount} known-missing official names; ${manualAudit.committedBuiltinNamesAbsentFromManualCount} labelled aliases/local extensions excluded from official coverage.`,
    `- Pine v6 grammar inventory: ${coveredGrammarEntries}/${manualAudit.manualGrammarEntries} official manual-index entries covered by ${manualAudit.committedGrammarConstructs} committed snippets; ${manualAudit.grammarEntriesAbsentFromCommittedListCount} known grammar gaps.`,
    `- Production worker load baseline: ${productionBaseline.compiled}/${productionBaseline.eligible} compiled; ${productionBaseline.fallback}/${productionBaseline.eligible} visible interpreter fallbacks.`,
    `- Production worker live-update baseline: ${productionBaseline.liveUpdates.compiled}/${productionBaseline.liveUpdates.total} compiled same-bar updates; ${productionBaseline.liveUpdates.fallback}/${productionBaseline.liveUpdates.total} visible fallbacks; ${productionBaseline.realtimeParity.workerMatched}/${productionBaseline.realtimeParity.totalUpdates} worker updates match fresh execution.`,
    `- Mobile TealScript capability baseline: ${mobileSupported.length}/${MOBILE_TEALSCRIPT_CAPABILITY_BASELINE.length} measured capability rows supported; remaining gap: ${mobileMissing.map((row) => row.capability).join('; ')}.`,
    '',
    `<!-- ${PINE_PARITY_HEADLINE_METRICS_END}`,
  ].join('\n');
}

export function replacePineParityHeadlineMetricsBlock(contents: string, block = buildPineParityHeadlineMetricsBlock()): string {
  const startIndex = contents.indexOf(PINE_PARITY_HEADLINE_METRICS_START);
  const endIndex = contents.indexOf(PINE_PARITY_HEADLINE_METRICS_END);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error('Missing generated Pine parity headline metrics block markers');
  }

  const endOfCommentIndex = contents.indexOf('-->', endIndex);
  if (endOfCommentIndex === -1) {
    throw new Error('Malformed generated Pine parity headline metrics end marker');
  }

  return `${contents.slice(0, startIndex)}${block}${contents.slice(endOfCommentIndex + '-->'.length)}`;
}

export async function checkPineParityHeadlineMetricsBlocks(paths = PINE_PARITY_HEADLINE_METRIC_DOC_PATHS): Promise<string[]> {
  const stalePaths: string[] = [];
  const block = buildPineParityHeadlineMetricsBlock();

  for (const path of paths) {
    const contents = await readFile(path, 'utf8');
    if (replacePineParityHeadlineMetricsBlock(contents, block) !== contents) {
      stalePaths.push(path);
    }
  }

  return stalePaths;
}

export async function writePineParityHeadlineMetricsBlocks(paths = PINE_PARITY_HEADLINE_METRIC_DOC_PATHS): Promise<void> {
  const block = buildPineParityHeadlineMetricsBlock();

  await Promise.all(
    paths.map(async (path) => {
      const contents = await readFile(path, 'utf8');
      await writeFile(path, replacePineParityHeadlineMetricsBlock(contents, block), 'utf8');
    }),
  );
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.includes('--check')) {
    const stalePaths = await checkPineParityHeadlineMetricsBlocks();
    if (stalePaths.length > 0) {
      process.stderr.write(
        `Generated Pine parity headline metrics are stale. Run yarn workspace @tealstreet/tealscript pine:parity:metrics.\n${stalePaths.join('\n')}\n`,
      );
      process.exitCode = 1;
    }
    return;
  }

  await writePineParityHeadlineMetricsBlocks();
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
