import { describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';

import {
  PINE_PARITY_HEADLINE_METRICS_END,
  PINE_PARITY_HEADLINE_METRICS_START,
  PINE_PARITY_HEADLINE_METRIC_DOC_PATHS,
  checkPineParityHeadlineMetricsBlocks,
} from '../../scripts/update-pine-parity-headline-metrics.ts';

describe('Pine parity headline metrics docs', () => {
  it('keeps one structurally complete generated block per reviewer-facing document', async () => {
    for (const path of PINE_PARITY_HEADLINE_METRIC_DOC_PATHS) {
      const contents = await readFile(path, 'utf8');
      expect(contents.match(new RegExp(PINE_PARITY_HEADLINE_METRICS_START, 'g'))).toHaveLength(1);
      expect(contents.match(new RegExp(PINE_PARITY_HEADLINE_METRICS_END, 'g'))).toHaveLength(1);

      const start = contents.indexOf(PINE_PARITY_HEADLINE_METRICS_START);
      const end = contents.indexOf(PINE_PARITY_HEADLINE_METRICS_END);
      expect(start).toBeLessThan(end);
      expect(contents.slice(start, end)).toContain('Generated by `yarn workspace @tealstreet/tealscript pine:parity:metrics`.');
    }
  });

  it('fails when generated headline metric values are stale', async () => {
    await expect(checkPineParityHeadlineMetricsBlocks()).resolves.toEqual([]);
  });
});
