import { describe, expect, it } from 'vitest';

import { parse } from '../../src/parser';
import { checkProgram } from '../../src/semantic';
import { compatibilityBars, runCompatScript } from './fixtures';

interface OperandContract {
  call: string;
  parameter: string;
  kind: string;
  field: string;
  first: string;
  second: string;
  expectedFirst: string | number;
  expectedSecond: string | number;
  entry: number;
  cell: boolean;
  defaultValue?: string;
}

const contracts: readonly OperandContract[] = [
  {
    call: 'table.new',
    parameter: 'position',
    kind: 'string',
    field: 'position',
    first: 'position.top_left',
    second: 'position.bottom_right',
    expectedFirst: 'top_left',
    expectedSecond: 'bottom_right',
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'columns',
    kind: 'int',
    field: 'columns',
    first: '2',
    second: '3',
    expectedFirst: 2,
    expectedSecond: 3,
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'rows',
    kind: 'int',
    field: 'rows',
    first: '2',
    second: '3',
    expectedFirst: 2,
    expectedSecond: 3,
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'bgcolor',
    kind: 'color',
    field: 'bgcolor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'frame_color',
    kind: 'color',
    field: 'frameColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'frame_width',
    kind: 'int',
    field: 'frameWidth',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'border_color',
    kind: 'color',
    field: 'borderColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.new',
    parameter: 'border_width',
    kind: 'int',
    field: 'borderWidth',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1022,
    cell: false,
  },
  {
    call: 'table.set_position',
    parameter: 'position',
    kind: 'string',
    field: 'position',
    first: 'position.top_left',
    second: 'position.bottom_right',
    expectedFirst: 'top_left',
    expectedSecond: 'bottom_right',
    entry: 1024,
    cell: false,
  },
  {
    call: 'table.set_bgcolor',
    parameter: 'bgcolor',
    kind: 'color',
    field: 'bgcolor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1025,
    cell: false,
  },
  {
    call: 'table.set_frame_color',
    parameter: 'frame_color',
    kind: 'color',
    field: 'frameColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1026,
    cell: false,
  },
  {
    call: 'table.set_border_color',
    parameter: 'border_color',
    kind: 'color',
    field: 'borderColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1027,
    cell: false,
  },
  {
    call: 'table.set_frame_width',
    parameter: 'frame_width',
    kind: 'int',
    field: 'frameWidth',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1028,
    cell: false,
  },
  {
    call: 'table.set_border_width',
    parameter: 'border_width',
    kind: 'int',
    field: 'borderWidth',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1029,
    cell: false,
  },
  {
    call: 'table.cell_set_text',
    parameter: 'text',
    kind: 'string',
    field: 'text',
    first: '"first"',
    second: '"second"',
    expectedFirst: 'first',
    expectedSecond: 'second',
    entry: 1031,
    cell: true,
  },
  {
    call: 'table.cell_set_text_formatting',
    parameter: 'text_formatting',
    kind: 'text_format',
    field: 'textFormatting',
    first: 'text.format_bold',
    second: 'text.format_italic',
    expectedFirst: 'bold',
    expectedSecond: 'italic',
    entry: 1032,
    cell: true,
  },
  {
    call: 'table.cell_set_text_font_family',
    parameter: 'text_font_family',
    kind: 'string',
    field: 'textFontFamily',
    first: 'font.family_default',
    second: 'font.family_monospace',
    expectedFirst: 'default',
    expectedSecond: 'monospace',
    entry: 1033,
    cell: true,
  },
  {
    call: 'table.cell_set_tooltip',
    parameter: 'tooltip',
    kind: 'string',
    field: 'tooltip',
    first: '"first"',
    second: '"second"',
    expectedFirst: 'first',
    expectedSecond: 'second',
    entry: 1034,
    cell: true,
  },
  {
    call: 'table.cell_set_width',
    parameter: 'width',
    kind: 'int',
    field: 'width',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1035,
    cell: true,
  },
  {
    call: 'table.cell_set_width',
    parameter: 'width',
    kind: 'float',
    field: 'width',
    first: '12.25',
    second: '34.75',
    expectedFirst: 12.25,
    expectedSecond: 34.75,
    entry: 1035,
    cell: true,
  },
  {
    call: 'table.cell_set_height',
    parameter: 'height',
    kind: 'int',
    field: 'height',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1036,
    cell: true,
  },
  {
    call: 'table.cell_set_height',
    parameter: 'height',
    kind: 'float',
    field: 'height',
    first: '12.25',
    second: '34.75',
    expectedFirst: 12.25,
    expectedSecond: 34.75,
    entry: 1036,
    cell: true,
  },
  {
    call: 'table.cell_set_text_color',
    parameter: 'text_color',
    kind: 'color',
    field: 'textColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1037,
    cell: true,
  },
  {
    call: 'table.cell_set_text_halign',
    parameter: 'text_halign',
    kind: 'string',
    field: 'textHalign',
    first: 'text.align_left',
    second: 'text.align_right',
    expectedFirst: 'left',
    expectedSecond: 'right',
    entry: 1038,
    cell: true,
  },
  {
    call: 'table.cell_set_text_valign',
    parameter: 'text_valign',
    kind: 'string',
    field: 'textValign',
    first: 'text.align_top',
    second: 'text.align_bottom',
    expectedFirst: 'top',
    expectedSecond: 'bottom',
    entry: 1039,
    cell: true,
  },
  {
    call: 'table.cell_set_text_size',
    parameter: 'text_size',
    kind: 'int',
    field: 'textSize',
    first: '1',
    second: '2',
    expectedFirst: '1',
    expectedSecond: '2',
    entry: 1040,
    cell: true,
  },
  {
    call: 'table.cell_set_text_size',
    parameter: 'text_size',
    kind: 'string',
    field: 'textSize',
    first: 'size.small',
    second: 'size.large',
    expectedFirst: 'small',
    expectedSecond: 'large',
    entry: 1040,
    cell: true,
  },
  {
    call: 'table.cell_set_bgcolor',
    parameter: 'bgcolor',
    kind: 'color',
    field: 'bgcolor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1041,
    cell: true,
  },
  {
    call: 'table.cell_set_bgcolor',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1041,
    cell: true,
    defaultValue: '#123456',
  },
  {
    call: 'table.cell_set_bgcolor',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1041,
    cell: true,
    defaultValue: '#123456',
  },
  {
    call: 'table.cell_set_height',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1036,
    cell: true,
    defaultValue: '12.25',
  },
  {
    call: 'table.cell_set_height',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1036,
    cell: true,
    defaultValue: '12.25',
  },
  {
    call: 'table.cell_set_text',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1031,
    cell: true,
    defaultValue: '"first"',
  },
  {
    call: 'table.cell_set_text',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1031,
    cell: true,
    defaultValue: '"first"',
  },
  {
    call: 'table.cell_set_text_color',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1037,
    cell: true,
    defaultValue: '#123456',
  },
  {
    call: 'table.cell_set_text_color',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1037,
    cell: true,
    defaultValue: '#123456',
  },
  {
    call: 'table.cell_set_text_font_family',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1033,
    cell: true,
    defaultValue: 'font.family_default',
  },
  {
    call: 'table.cell_set_text_font_family',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1033,
    cell: true,
    defaultValue: 'font.family_default',
  },
  {
    call: 'table.cell_set_text_formatting',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1032,
    cell: true,
    defaultValue: 'text.format_bold',
  },
  {
    call: 'table.cell_set_text_formatting',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1032,
    cell: true,
    defaultValue: 'text.format_bold',
  },
  {
    call: 'table.cell_set_text_halign',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1038,
    cell: true,
    defaultValue: 'text.align_left',
  },
  {
    call: 'table.cell_set_text_halign',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1038,
    cell: true,
    defaultValue: 'text.align_left',
  },
  {
    call: 'table.cell_set_text_size',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1040,
    cell: true,
    defaultValue: 'size.small',
  },
  {
    call: 'table.cell_set_text_size',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1040,
    cell: true,
    defaultValue: 'size.small',
  },
  {
    call: 'table.cell_set_text_valign',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1039,
    cell: true,
    defaultValue: 'text.align_top',
  },
  {
    call: 'table.cell_set_text_valign',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1039,
    cell: true,
    defaultValue: 'text.align_top',
  },
  {
    call: 'table.cell_set_tooltip',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1034,
    cell: true,
    defaultValue: '"first"',
  },
  {
    call: 'table.cell_set_tooltip',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1034,
    cell: true,
    defaultValue: '"first"',
  },
  {
    call: 'table.cell_set_width',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1035,
    cell: true,
    defaultValue: '12.25',
  },
  {
    call: 'table.cell_set_width',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1035,
    cell: true,
    defaultValue: '12.25',
  },
  {
    call: 'table.cell',
    parameter: 'text',
    kind: 'string',
    field: 'text',
    first: '"first"',
    second: '"second"',
    expectedFirst: 'first',
    expectedSecond: 'second',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_formatting',
    kind: 'text_format',
    field: 'textFormatting',
    first: 'text.format_bold',
    second: 'text.format_italic',
    expectedFirst: 'bold',
    expectedSecond: 'italic',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_font_family',
    kind: 'string',
    field: 'textFontFamily',
    first: 'font.family_default',
    second: 'font.family_monospace',
    expectedFirst: 'default',
    expectedSecond: 'monospace',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'tooltip',
    kind: 'string',
    field: 'tooltip',
    first: '"first"',
    second: '"second"',
    expectedFirst: 'first',
    expectedSecond: 'second',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'width',
    kind: 'int',
    field: 'width',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'width',
    kind: 'float',
    field: 'width',
    first: '12.25',
    second: '34.75',
    expectedFirst: 12.25,
    expectedSecond: 34.75,
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'height',
    kind: 'int',
    field: 'height',
    first: '1',
    second: '2',
    expectedFirst: 1,
    expectedSecond: 2,
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'height',
    kind: 'float',
    field: 'height',
    first: '12.25',
    second: '34.75',
    expectedFirst: 12.25,
    expectedSecond: 34.75,
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_color',
    kind: 'color',
    field: 'textColor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_halign',
    kind: 'string',
    field: 'textHalign',
    first: 'text.align_left',
    second: 'text.align_right',
    expectedFirst: 'left',
    expectedSecond: 'right',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_valign',
    kind: 'string',
    field: 'textValign',
    first: 'text.align_top',
    second: 'text.align_bottom',
    expectedFirst: 'top',
    expectedSecond: 'bottom',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_size',
    kind: 'int',
    field: 'textSize',
    first: '1',
    second: '2',
    expectedFirst: '1',
    expectedSecond: '2',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'text_size',
    kind: 'string',
    field: 'textSize',
    first: 'size.small',
    second: 'size.large',
    expectedFirst: 'small',
    expectedSecond: 'large',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'bgcolor',
    kind: 'color',
    field: 'bgcolor',
    first: '#123456',
    second: '#ABCDEF',
    expectedFirst: '#123456',
    expectedSecond: '#ABCDEF',
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'column',
    kind: 'int',
    field: 'column',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1030,
    cell: true,
  },
  {
    call: 'table.cell',
    parameter: 'row',
    kind: 'int',
    field: 'row',
    first: '0',
    second: '1',
    expectedFirst: 0,
    expectedSecond: 1,
    entry: 1030,
    cell: true,
  },
];

function declaration(contract: OperandContract, qualifier: string): string {
  if (qualifier === 'input') {
    const input =
      contract.kind === 'text_format'
        ? `input.bool(true) ? ${contract.first} : ${contract.second}`
        : `input.${contract.kind}(${contract.first})`;
    return `${contract.kind === 'text_format' ? 'input text_format ' : ''}operand = ${input}`;
  }
  return `${qualifier} ${contract.kind} operand = ${qualifier === 'series' ? `bar_index == 1 ? ${contract.second} : ${contract.first}` : contract.first}`;
}

function call(contract: OperandContract, method: boolean): string {
  if (contract.call === 'table.new') {
    const args = Object.entries({
      position: 'position.top_left',
      columns: '2',
      rows: '2',
      [contract.parameter]: 'operand',
    })
      .reverse()
      .map(([name, value]) => `${name}=${value}`);
    return `id = table.new(${args.join(', ')})`;
  }
  let parameters: Record<string, string> = {};
  if (contract.cell) {
    parameters = { column: '0', row: '0' };
    if (contract.call === 'table.cell') parameters.text = '"old"';
    else parameters[contract.call.slice('table.cell_set_'.length)] = contract.defaultValue ?? contract.first;
  }
  const args = Object.entries({
    ...parameters,
    [contract.parameter]: 'operand',
    ...(!method ? { table_id: 'id' } : {}),
  })
    .reverse()
    .map(([name, value]) => `${name}=${value}`);
  return `id = table.new(position.top_left, 2, 2)
${method ? `id.${contract.call.split('.')[1]}` : contract.call}(${args.join(', ')})`;
}

// Prefixes preserve the changing middle operand even when table.new replaces an earlier table.
for (const contract of contracts) {
  for (const method of contract.call === 'table.new' ? [false] : [false, true]) {
    describe(`${contract.call} ${method ? 'method' : 'namespace'} ${contract.parameter} ${contract.kind} [${contract.entry}]`, () => {
      for (const qualifier of ['const', 'input', 'simple', 'series']) {
        it(`accepts and uses ${qualifier} operand`, () => {
          const source = `//@version=6
indicator("Table operand qualifiers")
${declaration(contract, qualifier)}
${call(contract, method)}`;
          const citation = `https://www.tradingview.com/pine-script-reference/v6/#fun_${contract.call}`;
          const checked = checkProgram(parse(source));
          expect(checked.diagnostics, citation).toEqual([]);
          expect(checked.symbols.find((symbol) => symbol.name === 'operand')?.type, citation).toMatchObject({
            kind: contract.kind === 'text_format' ? 'udt' : contract.kind,
            qualifier,
          });
          for (const count of [1, 2, 3]) {
            const result = runCompatScript(source, { bars: compatibilityBars.slice(0, count) });
            expect(result.errors, citation).toEqual([]);
            expect(result.profile.compiledBarErrors?.count ?? 0, citation).toBe(0);
            const table = result.drawings.filter((drawing) => drawing.type === 'table').at(-1);
            const target = contract.cell ? table?.cells.at(-1) : table;
            expect(target, citation).toEqual(
              expect.objectContaining({
                [contract.field]:
                  qualifier === 'series' && count === 2 ? contract.expectedSecond : contract.expectedFirst,
              }),
            );
          }
        });
      }
    });
  }
}
