/**
 * Tealscript Runtime exports
 */

export { Series, seriesFrom, constantSeries, getValue, isSeries, type SeriesSnapshot, type MaybeSeriesValue } from './series';

export {
  createPineArray,
  isPineArray,
  getArraySize,
  getArrayValue,
  setArrayValue,
  pushArrayValue,
  popArrayValue,
  shiftArrayValue,
  unshiftArrayValue,
  clearArray,
  copyArray,
  firstArrayValue,
  lastArrayValue,
  includesArrayValue,
  indexOfArrayValue,
  lastIndexOfArrayValue,
  insertArrayValue,
  removeArrayValue,
  minArrayValue,
  maxArrayValue,
  sumArrayValue,
  avgArrayValue,
  type PineArray,
} from './arrays';

export {
  createPineMatrix,
  eigenvaluesMatrixValue,
  eigenvectorsMatrixValue,
  isPineMatrix,
  isValidMatrix,
  isSquareMatrix,
  getMatrixRows,
  getMatrixColumns,
  getMatrixElementCount,
  getMatrixValue,
  setMatrixValue,
  copyMatrix,
  matrixRow,
  matrixColumn,
  fillMatrix,
  reshapeMatrix,
  addMatrixRow,
  addMatrixColumn,
  removeMatrixRow,
  removeMatrixColumn,
  swapMatrixRows,
  swapMatrixColumns,
  reverseMatrix,
  transposeMatrix,
  avgMatrixValue,
  minMatrixValue,
  maxMatrixValue,
  medianMatrixValue,
  modeMatrixValue,
  pinvMatrixValue,
  type PineMatrix,
} from './matrices';

export {
  createPineMap,
  isPineMap,
  getMapSize,
  putMapValue,
  getMapValue,
  containsMapKey,
  removeMapValue,
  clearMap,
  copyMap,
  mapKeys,
  mapValues,
  putAllMapValues,
  mapEntries,
  type PineMap,
} from './maps';

export {
  createPineUdtObject,
  isPineUdtObject,
  getUdtField,
  setUdtField,
  copyUdtObject,
  type PineUdtObject,
} from './objects';

export {
  ExecutionContext,
  createContext,
  type Bar,
  type BarState,
  type SessionClassificationInfo,
  type SessionClosureInfo,
  type SessionClosureKind,
  type SymInfo,
  type TimeframeInfo,
  type PlotOutput,
  type PlotStyle,
  type PlotLineStyle,
  type AlertEvent,
  type AlertFrequency,
  type AlertOutput,
  type LogLevel,
  type LogOutput,
  type InputDefinition,
} from './context';

export {
  createDefaultStrategySettings,
  cancelAllStrategyOrders,
  cancelStrategyOrder,
  cloneStrategyIntrabarContext,
  cloneStrategyLedger,
  createDefaultStrategyOhlcIntrabarContext,
  createStrategyOrder,
  fillStrategyMarketOrder,
  fillPendingStrategyOrders,
  fillPendingStrategyOrdersOnTicks,
  createStrategyLedger,
  createStrategyPosition,
  InMemoryStrategyIntrabarDatafeed,
  selectStrategyIntrabarContext,
  strategyIntrabarContextKey,
  submitStrategyOrder,
  type StrategyDirection,
  type StrategyEquityPoint,
  type StrategyExecutionTick,
  type StrategyExecutionTickKind,
  type StrategyFill,
  type StrategyIntrabarContext,
  type StrategyIntrabarDatafeed,
  type StrategyIntrabarFailure,
  type StrategyIntrabarRequest,
  type StrategyIntrabarResult,
  type StrategyIntrabarSelectionOptions,
  type StrategyIntrabarSource,
  type StrategyIntrabarSuccess,
  type StrategyIntrabarUnavailableReason,
  type StrategyLedger,
  type StrategyLedgerSettings,
  type StrategyOcaType,
  type StrategyOrder,
  type StrategyOrderInput,
  type StrategyOrderStatus,
  type StrategyOrderType,
  type StrategyPosition,
  type StrategyQuantityType,
  type StrategyTrade,
} from './strategy';

export type {
  DrawingOutput,
  LabelDrawingOutput,
  LineDrawingOutput,
  LineFillDrawingOutput,
  BoxDrawingOutput,
  PolylineDrawingOutput,
  TableCellDrawingOutput,
  TableMergedCellDrawingOutput,
  TableDrawingOutput,
} from './drawings/types';

export { Scope, createRootScope, type VarKind, type VariableEntry, type ScopeSnapshot } from './scope';

export {
  executeScript,
  type ExecutionResult,
  type ExecutionError,
  type RuntimeProfile,
  type IndicatorDeclarationMetadata,
  type TealscriptExecutionOptions,
  type TealscriptRuntimeOptions,
} from './compiledOnly';

export {
  DEFAULT_TEALSCRIPT_EXECUTION_BACKEND,
  applyTealscriptBackendSelectionProfile,
  selectTealscriptExecutionBackend,
  type TealscriptBackendSelection,
  type TealscriptBackendSelectionOptions,
  type TealscriptBackendSelectionSource,
  type TealscriptExecutionBackend,
} from './backendSelection';

export {
  executeSelectedTealscriptBackend,
  type SelectedTealscriptExecutionOptions,
} from './executeSelected';

export {
  CacheBackedRequestDatafeed,
  InMemoryRequestDatafeed,
  corporateActionContextKey,
  corporateActionRequestKey,
  currencyRateRequestKey,
  economicRequestKey,
  financialMetricContextKey,
  financialRequestKey,
  footprintRequestKey,
  quandlRequestKey,
  requestDatafeedKey,
  requestSeriesKey,
  seedCorporateAction,
  seedCurrencyRate,
  seedEconomicSeries,
  seedFinancialMetric,
  seedFootprints,
  seedQuandlSeries,
  seedRequestSymbol,
  selectCorporateActionField,
  workerRequestDataCacheKey,
  type RequestCorporateActionContext,
  type RequestCorporateActionEvent,
  type RequestCorporateActionKind,
  type RequestCorporateActionQuery,
  type RequestCorporateActionValue,
  type RequestCurrencyRateContext,
  type RequestCurrencyRateQuery,
  type RequestDataContext,
  type RequestDatafeed,
  type RequestDatafeedErrorCode,
  type RequestDatafeedFailure,
  type RequestDatafeedKey,
  type RequestDatafeedQuery,
  type RequestDatafeedResult,
  type RequestDatafeedSuccess,
  type RequestEconomicSeriesContext,
  type RequestEconomicSeriesQuery,
  type RequestFinancialMetricContext,
  type RequestFinancialMetricQuery,
  type RequestFootprintContext,
  type RequestFootprintData,
  type RequestFootprintQuery,
  type RequestVolumeRowData,
  type RequestQuandlSeriesContext,
  type RequestQuandlSeriesQuery,
  type RequestSeriesContext,
  type RequestSeriesFamily,
  type RequestSeriesPoint,
  type RequestSeriesQuery,
  type RequestSeriesResult,
  type RequestSeriesSuccess,
  type WorkerRequestDataCacheEntry,
  type WorkerRequestDataCacheKind,
} from './requestDatafeed';
