export type BuiltinGlobalTypeKind = 'float' | 'int';
export type BuiltinGlobalQualifier = 'series';
export interface BuiltinGlobalTypeMetadata {
  kind: BuiltinGlobalTypeKind;
  qualifier: BuiltinGlobalQualifier;
}

export const BUILTIN_GLOBALS = new Set([
  'bar_index',
  'close',
  'hl2',
  'hlc3',
  'high',
  'last_bar_index',
  'low',
  'na',
  'ohlc4',
  'open',
  'time',
  'time_close',
  'time_tradingday',
  'timenow',
  'last_bar_time',
  'volume',
]);

export const BUILTIN_GLOBAL_TYPES = new Map<string, BuiltinGlobalTypeMetadata>([
  ['bar_index', { kind: 'int', qualifier: 'series' }],
  ['close', { kind: 'float', qualifier: 'series' }],
  ['high', { kind: 'float', qualifier: 'series' }],
  ['hl2', { kind: 'float', qualifier: 'series' }],
  ['hlc3', { kind: 'float', qualifier: 'series' }],
  ['last_bar_index', { kind: 'int', qualifier: 'series' }],
  ['last_bar_time', { kind: 'int', qualifier: 'series' }],
  ['low', { kind: 'float', qualifier: 'series' }],
  ['ohlc4', { kind: 'float', qualifier: 'series' }],
  ['open', { kind: 'float', qualifier: 'series' }],
  ['time', { kind: 'int', qualifier: 'series' }],
  ['time_close', { kind: 'int', qualifier: 'series' }],
  ['time_tradingday', { kind: 'int', qualifier: 'series' }],
  ['timenow', { kind: 'int', qualifier: 'series' }],
  ['volume', { kind: 'float', qualifier: 'series' }],
]);

export const CALENDAR_FUNCTION_NAMES = new Set([
  'year',
  'month',
  'weekofyear',
  'dayofmonth',
  'dayofweek',
  'hour',
  'minute',
  'second',
]);

export const BUILTIN_NAMESPACES = new Set([
  'adjustment',
  'alert',
  'array',
  'barmerge',
  'barstate',
  'box',
  'chart',
  'color',
  'currency',
  'dividends',
  'display',
  'earnings',
  'extend',
  'format',
  'hline',
  'input',
  'label',
  'line',
  'linefill',
  'location',
  'log',
  'map',
  'math',
  'matrix',
  'order',
  'plot',
  'polyline',
  'position',
  'request',
  'runtime',
  'scale',
  'session',
  'shape',
  'size',
  'splits',
  'str',
  'strategy',
  'syminfo',
  'ta',
  'table',
  'ticker',
  'timeframe',
  'xloc',
  'yloc',
]);

export const EXPORTABLE_BUILTIN_CONSTANTS = new Set([
  'alert.freq_all',
  'alert.freq_once_per_bar',
  'alert.freq_once_per_bar_close',
  'barmerge.gaps_off',
  'barmerge.gaps_on',
  'barmerge.lookahead_off',
  'barmerge.lookahead_on',
  'color.aqua',
  'color.black',
  'color.blue',
  'color.fuchsia',
  'color.gray',
  'color.green',
  'color.lime',
  'color.maroon',
  'color.navy',
  'color.none',
  'color.olive',
  'color.orange',
  'color.purple',
  'color.red',
  'color.silver',
  'color.teal',
  'color.white',
  'color.yellow',
  'dividends.gross',
  'dividends.net',
  'earnings.actual',
  'earnings.estimate',
  'earnings.standardized',
  'hline.style_dashed',
  'hline.style_dotted',
  'hline.style_solid',
  'math.e',
  'math.phi',
  'math.pi',
  'plot.linestyle_dashed',
  'plot.linestyle_dotted',
  'plot.linestyle_solid',
  'plot.style_area',
  'plot.style_areabr',
  'plot.style_circles',
  'plot.style_columns',
  'plot.style_cross',
  'plot.style_histogram',
  'plot.style_line',
  'plot.style_linebr',
  'plot.style_stepline',
  'plot.style_stepline_diamond',
  'splits.denominator',
  'splits.numerator',
  'strategy.cash',
  'strategy.commission.cash_per_contract',
  'strategy.commission.cash_per_order',
  'strategy.commission.percent',
  'strategy.fixed',
  'strategy.long',
  'strategy.oca.cancel',
  'strategy.oca.none',
  'strategy.oca.reduce',
  'strategy.percent_of_equity',
  'strategy.short',
]);

export const EXPORTABLE_CONTEXT_MEMBER_CONSTANTS = new Map<string, Set<string>>([
  ['barstate', new Set(['isconfirmed', 'isfirst', 'ishistory', 'islast', 'islastconfirmedhistory', 'isnew', 'isrealtime'])],
  ['syminfo', new Set(['basecurrency', 'currency', 'description', 'main_tickerid', 'mintick', 'minmove', 'prefix', 'pricescale', 'root', 'session', 'ticker', 'tickerid', 'timezone', 'type'])],
  ['timeframe', new Set(['isdaily', 'isdwm', 'isintraday', 'isminutes', 'ismonthly', 'isseconds', 'isticks', 'isweekly', 'main_period', 'multiplier', 'period'])],
]);

export const BUILTIN_COLLECTION_MEMBER_METHODS = new Map<string, Set<string>>([
  ['array', new Set([
    'abs',
    'avg',
    'binary_search',
    'binary_search_leftmost',
    'binary_search_rightmost',
    'clear',
    'concat',
    'copy',
    'covariance',
    'every',
    'fill',
    'first',
    'get',
    'includes',
    'indexof',
    'insert',
    'join',
    'last',
    'lastindexof',
    'max',
    'median',
    'min',
    'mode',
    'percentrank',
    'percentile_linear_interpolation',
    'percentile_nearest_rank',
    'pop',
    'push',
    'range',
    'remove',
    'reverse',
    'set',
    'shift',
    'size',
    'slice',
    'some',
    'sort',
    'sort_indices',
    'standardize',
    'stdev',
    'sum',
    'unshift',
    'variance',
  ])],
  ['map', new Set(['clear', 'contains', 'copy', 'get', 'keys', 'put', 'put_all', 'remove', 'size', 'values'])],
  ['matrix', new Set([
    'add_col',
    'add_column',
    'add_row',
    'avg',
    'col',
    'column',
    'columns',
    'concat',
    'copy',
    'det',
    'diff',
    'eigenvalues',
    'eigenvectors',
    'elements_count',
    'fill',
    'get',
    'inv',
    'is_antidiagonal',
    'is_binary',
    'is_diagonal',
    'is_identity',
    'is_square',
    'is_stochastic',
    'is_symmetric',
    'is_triangular',
    'is_valid',
    'is_zero',
    'kron',
    'max',
    'median',
    'min',
    'mode',
    'mult',
    'pinv',
    'pow',
    'rank',
    'remove_col',
    'remove_column',
    'remove_row',
    'reshape',
    'reverse',
    'row',
    'rows',
    'set',
    'sort',
    'submatrix',
    'sum',
    'swap_columns',
    'swap_rows',
    'trace',
    'transpose',
  ])],
]);

export function isExportableBuiltinConstantPath(path: string[]): boolean {
  if (path.length < 2) return false;

  const namespace = path.slice(0, -1).join('.');
  const property = path[path.length - 1]!;
  if (EXPORTABLE_BUILTIN_CONSTANTS.has(path.join('.'))) return true;

  return path.length === 2 && (EXPORTABLE_CONTEXT_MEMBER_CONSTANTS.get(namespace)?.has(property) ?? false);
}
