/**
 * @tealstreet/tealscript
 *
 * A browser-based Tealscript runtime for TradingView-compatible indicators.
 */

// Parser
export {
  compatibilityFailureClasses,
  compatibilityStageStatuses,
  compatibilityStages,
  createCompatibilityRunOutcome,
  createPineCompatibilityCoverageIndex,
  createPineScriptLedger,
  formatPineCompatibilityCoverageJson,
  formatPineCompatibilityCoverageMarkdown,
  formatPineCompatibilityCorpusJson,
  formatPineCompatibilityCorpusMarkdown,
  getCompiledFallbackBaselineGroup,
  normalizeCompatibilityStageOutcomes,
  PINE_COMPILED_FALLBACK_BASELINE,
  PINE_COMPATIBILITY_SCHEMA_VERSION,
  runPineCompatibilityCorpus,
  runPineCompatibilityLedger,
  summarizeCompiledFallbackReasons,
  summarizeCompatibilityOutcome,
  summarizePineCompatibilityCorpus,
  validateCompatibilityStageSequence,
  validateCompatibilityStageOutcome,
  validatePineScriptLedger,
  validatePineScriptLedgerEntry,
  type CompatibilityDiagnostic,
  type CompiledFallbackBaseline,
  type CompiledFallbackBaselineGroup,
  type CompiledFallbackReasonSummary,
  type CompatibilityFailureClass,
  type CompatibilityRunOutcome,
  type CompatibilityRunSummary,
  type CompatibilityStage,
  type CompatibilityStageOutcome,
  type CompatibilityStageStatus,
  type PineCompatibilityCorpusCase,
  type PineCompatibilityCorpusStages,
  type PineCompatibilityCorpusRun,
  type PineCompatibilityCorpusSummary,
  type PineCompatibilityCoverageIndex,
  type PineCompatibilityStageProvider,
  type PineScriptCategory,
  type PineScriptLedger,
  type PineScriptLedgerEntry,
  type PineScriptLedgerSource,
  type PineScriptLicenseStatus,
  type PineScriptSourceKind,
  type PineScriptStoragePolicy,
  type PineVersion,
} from './compat';

export {
  createPineParseSemanticStageOutcomes,
} from './compat/sourceStages';

export {
  classifyPineCompatibilitySource,
  type PineSourceClassificationOptions,
} from './compat/sourceClassifier';

export {
  // Parser functions
  parse,
  validate,
  formatParseError,
  TealscriptParseError,
  type ParseOptions,
  type ParseResult,
  type ParseStartRule,
  // AST types
  type Program,
  type Statement,
  type Expression,
  type IndicatorDeclaration,
  type LibraryDeclaration,
  type ImportDeclaration,
  type TypeDeclaration,
  type TypeFieldDeclaration,
  type EnumDeclaration,
  type EnumFieldDeclaration,
  type VariableDeclaration,
  type AssignmentStatement,
  type ExpressionStatement,
  type IfStatement,
  type ForStatement,
  type WhileStatement,
  type BreakStatement,
  type ContinueStatement,
  type Identifier,
  type Literal,
  type NumericLiteral,
  type StringLiteral,
  type BooleanLiteral,
  type ColorLiteral,
  type BinaryExpression,
  type UnaryExpression,
  type ConditionalExpression,
  type CallExpression,
  type MemberExpression,
  type IndexExpression,
  type ArrayExpression,
  type NaExpression,
  type TypeAnnotation,
  type SourceLocation,
  // Type guards
  isExpression,
  isStatement,
  isLiteral,
} from './parser';

// Runtime
export {
  // Engine
  TealscriptEngine,
  executeScript,
  executeSelectedTealscriptBackend,
  DEFAULT_TEALSCRIPT_EXECUTION_BACKEND,
  applyTealscriptBackendSelectionProfile,
  selectTealscriptExecutionBackend,
  type ExecutionResult,
  type ExecutionError,
  type RuntimeProfile,
  type IndicatorDeclarationMetadata,
  type TealscriptEngineOptions,
  type TealscriptRuntimeOptions,
  type SelectedTealscriptExecutionOptions,
  type TealscriptBackendSelection,
  type TealscriptBackendSelectionOptions,
  type TealscriptBackendSelectionSource,
  type TealscriptExecutionBackend,
  // Context
  ExecutionContext,
  createContext,
  type Bar,
  type BarState,
  type SessionClassificationInfo,
  type SessionClosureInfo,
  type SessionClosureKind,
  type SymInfo,
  type TimeframeInfo,
  type PlotOutput,
  type PlotStyle,
  type PlotLineStyle,
  type DrawingOutput,
  type LabelDrawingOutput,
  type LineDrawingOutput,
  type LineFillDrawingOutput,
  type BoxDrawingOutput,
  type PolylineDrawingOutput,
  type TableCellDrawingOutput,
  type TableMergedCellDrawingOutput,
  type TableDrawingOutput,
  type AlertEvent,
  type AlertFrequency,
  type AlertOutput,
  type LogLevel,
  type LogOutput,
  type InputDefinition,
  createDefaultStrategySettings,
  cancelAllStrategyOrders,
  cancelStrategyOrder,
  cloneStrategyIntrabarContext,
  cloneStrategyLedger,
  createDefaultStrategyOhlcIntrabarContext,
  createStrategyOrder,
  fillStrategyMarketOrder,
  fillPendingStrategyOrders,
  fillPendingStrategyOrdersOnTicks,
  createStrategyLedger,
  createStrategyPosition,
  InMemoryStrategyIntrabarDatafeed,
  selectStrategyIntrabarContext,
  strategyIntrabarContextKey,
  submitStrategyOrder,
  type StrategyDirection,
  type StrategyEquityPoint,
  type StrategyExecutionTick,
  type StrategyExecutionTickKind,
  type StrategyFill,
  type StrategyIntrabarContext,
  type StrategyIntrabarDatafeed,
  type StrategyIntrabarFailure,
  type StrategyIntrabarRequest,
  type StrategyIntrabarResult,
  type StrategyIntrabarSelectionOptions,
  type StrategyIntrabarSource,
  type StrategyIntrabarSuccess,
  type StrategyIntrabarUnavailableReason,
  type StrategyLedger,
  type StrategyLedgerSettings,
  type StrategyOcaType,
  type StrategyOrder,
  type StrategyOrderInput,
  type StrategyOrderStatus,
  type StrategyOrderType,
  type StrategyPosition,
  type StrategyQuantityType,
  type StrategyTrade,
  // Request datafeed
  CacheBackedRequestDatafeed,
  InMemoryRequestDatafeed,
  corporateActionContextKey,
  corporateActionRequestKey,
  currencyRateRequestKey,
  economicRequestKey,
  financialMetricContextKey,
  financialRequestKey,
  footprintRequestKey,
  quandlRequestKey,
  requestDatafeedKey,
  requestSeriesKey,
  seedCorporateAction,
  seedCurrencyRate,
  seedEconomicSeries,
  seedFinancialMetric,
  seedFootprints,
  seedQuandlSeries,
  seedRequestSymbol,
  selectCorporateActionField,
  workerRequestDataCacheKey,
  type RequestCorporateActionContext,
  type RequestCorporateActionEvent,
  type RequestCorporateActionKind,
  type RequestCorporateActionQuery,
  type RequestCorporateActionValue,
  type RequestCurrencyRateContext,
  type RequestCurrencyRateQuery,
  type RequestDataContext,
  type RequestDatafeed,
  type RequestDatafeedErrorCode,
  type RequestDatafeedFailure,
  type RequestDatafeedKey,
  type RequestDatafeedQuery,
  type RequestDatafeedResult,
  type RequestDatafeedSuccess,
  type RequestEconomicSeriesContext,
  type RequestEconomicSeriesQuery,
  type RequestFinancialMetricContext,
  type RequestFinancialMetricQuery,
  type RequestFootprintContext,
  type RequestFootprintData,
  type RequestFootprintQuery,
  type RequestVolumeRowData,
  type RequestQuandlSeriesContext,
  type RequestQuandlSeriesQuery,
  type RequestSeriesContext,
  type RequestSeriesFamily,
  type RequestSeriesPoint,
  type RequestSeriesQuery,
  type RequestSeriesResult,
  type RequestSeriesSuccess,
  type WorkerRequestDataCacheEntry,
  type WorkerRequestDataCacheKind,
  // Series
  Series,
  seriesFrom,
  constantSeries,
  getValue,
  isSeries,
  type SeriesSnapshot,
  type MaybeSeriesValue,
  // Scope
  Scope,
  createRootScope,
  type VarKind,
  type VariableEntry,
  type ScopeSnapshot,
} from './runtime';

// Semantic checker
export {
  checkProgram,
  type SemanticCheckResult,
  type SemanticCheckOptions,
  type SemanticDiagnostic,
  type SemanticDiagnosticSeverity,
  type SemanticQualifier,
  type SemanticSymbol,
  type SemanticSymbolKind,
  type SemanticType,
  type SemanticTypeKind,
} from './semantic';

// Worker
export {
  TealscriptWorker,
  TealscriptWorkerFactory,
  type TealscriptWorkerOptions,
  type WorkerResult,
  type WorkerError,
  type ResultCallback,
  type ErrorCallback,
  // Protocol types
  type ToWorkerMessage,
  type FromWorkerMessage,
  type WorkerOutputBundle,
  type NormalizedWorkerOutputBundle,
  type WorkerOutputMetadata,
  type InitMessage,
  type UpdateBarsMessage,
  type UpdateBarMessage,
  type SetInputsMessage,
  type DisposeMessage,
  type ReadyMessage,
  type ResultMessage,
  type ErrorMessage,
  type ParseErrorMessage,
  createResultMessage,
  getResultOutput,
} from './worker';
